import { Camera, CheckCircle2, ScanLine, ShieldCheck } from 'lucide-react';
import { workflowStore } from '../../lib/workflowStore';

type Props={tyreId:string};

export function TyreCameraEvidenceSection({tyreId}:Props){
  const scans=workflowStore.tyreScans().filter(scan=>scan.tyreId===tyreId).sort((a,b)=>b.capturedAt.localeCompare(a.capturedAt));
  const latest=scans[0];
  if(!latest)return <section className="rounded-[24px] bg-white p-5 ring-1 ring-black/[0.045]"><div className="flex items-start gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#F5F4F0] text-zinc-400"><Camera size={18}/></div><div><h2 className="text-lg font-extrabold text-brand-ink">Camera inspection evidence</h2><p className="mt-1 text-xs leading-5 text-zinc-500">No phone-camera scan has been transferred to this tyre yet. Camera results will appear here without replacing verified workshop measurements.</p></div></div></section>;
  return <section className="overflow-hidden rounded-[24px] bg-white ring-1 ring-black/[0.045]"><div className="flex flex-col gap-4 border-b border-black/[0.05] p-5 sm:flex-row sm:items-start sm:justify-between"><div className="flex items-start gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-orange-50 text-brand-orange"><ScanLine size={18}/></div><div><p className="text-xs font-bold uppercase tracking-[.12em] text-brand-orange">Camera inspection evidence</p><h2 className="mt-1 text-lg font-extrabold text-brand-ink">Latest phone scan</h2><p className="mt-1 text-xs text-zinc-500">{new Date(latest.capturedAt).toLocaleString('en-ZA',{dateStyle:'medium',timeStyle:'short'})} · {latest.position}</p></div></div><span className="w-fit rounded-full bg-amber-50 px-3 py-1.5 text-xs font-bold text-amber-700">{latest.verification}</span></div><div className="grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-4"><div><p className="text-xs font-bold text-zinc-400">Tread estimate</p><p className="mt-1 text-lg font-extrabold text-brand-ink">{latest.estimatedTreadMm?.toFixed(1)??'—'} mm</p></div><div><p className="text-xs font-bold text-zinc-400">Wear pattern</p><p className="mt-1 text-sm font-extrabold text-brand-ink">{latest.wearPattern}</p></div><div><p className="text-xs font-bold text-zinc-400">Visual confidence</p><p className="mt-1 text-lg font-extrabold text-brand-ink">{latest.confidence}%</p></div><div><p className="text-xs font-bold text-zinc-400">Source</p><p className="mt-1 text-sm font-extrabold text-brand-ink">{latest.source}</p></div></div><div className="mx-5 mb-5 rounded-xl bg-[#F7F6F2] p-4"><div className="flex items-start gap-3"><ShieldCheck size={17} className="mt-0.5 shrink-0 text-brand-orange"/><div><p className="text-sm font-extrabold text-brand-ink">Recommendation</p><p className="mt-1 text-xs leading-5 text-zinc-500">{latest.recommendation}</p><p className="mt-3 flex items-center gap-2 text-xs font-bold text-zinc-400"><CheckCircle2 size={14}/>Stored as {latest.analysisMode}; verified measurements remain authoritative.</p></div></div></div>{scans.length>1&&<div className="border-t border-black/[0.05] px-5 py-3 text-xs font-bold text-zinc-400">{scans.length} camera scans stored in this tyre passport</div>}</section>;
}
