import type { DemoJobCard } from './workflowStore';
import { reserveTyreStock } from '../services/inventoryService';
import { tyres } from '../data/mock';

export type TyreLifecycleEvent={id:string;tyreId?:string;registration:string;position?:string;type:'Fitment'|'Rotation'|'Removal'|'Disposal'|'Retread'|'Warranty return';fromPosition?:string;toPosition?:string;reason?:string;destination?:string;odometer?:number;createdAt:string;jobCardId?:string;sku?:string;notes?:string};
export type RecallCampaign={id:string;manufacturer:string;model:string;dotRange:string;severity:'Advisory'|'Safety'|'Critical';status:'Active'|'Closed';affectedTyres:number;matchedVehicles:string[];action:string;createdAt:string};
export type SupplierOrder={id:string;supplier:string;branch:string;status:'Draft'|'Submitted'|'Partially received'|'Received'|'Cancelled';createdAt:string;expectedDate:string;items:{sku:string;description:string;quantity:number;unitCost:number;received:number}[]};
export type AuditEntry={id:string;at:string;actor:string;action:string;entityType:string;entityId:string;details:string};
export type OfflineInspectionDraft={id:string;registration:string;customer:string;odometer:number;updatedAt:string;status:'Offline draft'|'Ready to sync'|'Synced';payload:unknown};
const EVENTS='tyretrack.lifecycle.events',RECALLS='tyretrack.lifecycle.recalls',ORDERS='tyretrack.lifecycle.orders',AUDIT='tyretrack.lifecycle.audit',OFFLINE='tyretrack.lifecycle.offline';
const read=<T,>(key:string,seed:T):T=>{if(typeof window==='undefined')return seed;const raw=localStorage.getItem(key);if(!raw){localStorage.setItem(key,JSON.stringify(seed));return seed}try{return JSON.parse(raw) as T}catch{return seed}};
const write=<T,>(key:string,value:T)=>{if(typeof window!=='undefined')localStorage.setItem(key,JSON.stringify(value));return value};
const seedEvents:TyreLifecycleEvent[]=[{id:'EVT-001',tyreId:'TYR-3004',registration:'ND 452-981',position:'Rear Right',type:'Fitment',odometer:20000,createdAt:'2025-11-18T08:00:00Z',notes:'Original fitment'}];
const seedRecalls:RecallCampaign[]=[{id:'RC-2026-014',manufacturer:'Continental',model:'UltraContact',dotRange:'DOT 1026-1826',severity:'Safety',status:'Active',affectedTyres:6,matchedVehicles:['ND 452-981','ND 667-220'],action:'Inspect sidewall batch marking and replace affected tyres.',createdAt:'2026-08-12T07:00:00Z'}];
const seedOrders:SupplierOrder[]=[{id:'PO-260818-01',supplier:'Continental SA',branch:'Durban Central',status:'Submitted',createdAt:'2026-08-18T06:00:00Z',expectedDate:'2026-08-20',items:[{sku:'CON-UC-2055516',description:'Continental UltraContact 205/55 R16',quantity:12,unitCost:1420,received:0}]}];
const seedAudit:AuditEntry[]=[{id:'AUD-1',at:'2026-08-18T07:42:00Z',actor:'N. Mthembu',action:'Quotation sent',entityType:'Job card',entityId:'JOB-4001',details:'Quote QT-260818-001 sent to customer portal.'}];
export const lifecycleStore={events:()=>read(EVENTS,seedEvents),saveEvents:(v:TyreLifecycleEvent[])=>write(EVENTS,v),recalls:()=>read(RECALLS,seedRecalls),saveRecalls:(v:RecallCampaign[])=>write(RECALLS,v),orders:()=>read(ORDERS,seedOrders),saveOrders:(v:SupplierOrder[])=>write(ORDERS,v),audit:()=>read(AUDIT,seedAudit),saveAudit:(v:AuditEntry[])=>write(AUDIT,v),offlineDrafts:()=>read(OFFLINE,[] as OfflineInspectionDraft[]),saveOfflineDrafts:(v:OfflineInspectionDraft[])=>write(OFFLINE,v)};
export function addAudit(actor:string,action:string,entityType:string,entityId:string,details:string){const entry:AuditEntry={id:`AUD-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,at:new Date().toISOString(),actor,action,entityType,entityId,details};lifecycleStore.saveAudit([entry,...lifecycleStore.audit()]);return entry}
export function recordRotation(registration:string,moves:{tyreId:string;from:string;to:string}[],odometer:number){const now=new Date().toISOString();const events=moves.map((m,i):TyreLifecycleEvent=>({id:`ROT-${Date.now()}-${i}`,tyreId:m.tyreId,registration,type:'Rotation',fromPosition:m.from,toPosition:m.to,position:m.to,odometer,createdAt:now,reason:'Scheduled rotation'}));lifecycleStore.saveEvents([...events,...lifecycleStore.events()]);addAudit('Current user','Tyres rotated','Vehicle',registration,`${moves.length} tyre positions updated at ${odometer} km.`);return events}
export function recordRemoval(input:{tyreId:string;registration:string;position:string;reason:string;destination:string;odometer:number;jobCardId?:string}){const type:TyreLifecycleEvent['type']=input.destination==='Retread'?'Retread':input.destination==='Warranty return'?'Warranty return':input.destination==='Recycling'?'Disposal':'Removal';const event:TyreLifecycleEvent={id:`REM-${Date.now()}-${Math.random().toString(36).slice(2,5)}`,tyreId:input.tyreId,registration:input.registration,position:input.position,type,reason:input.reason,destination:input.destination,odometer:input.odometer,createdAt:new Date().toISOString(),jobCardId:input.jobCardId};lifecycleStore.saveEvents([event,...lifecycleStore.events()]);addAudit('Current user','Tyre removed','Tyre',input.tyreId,`${input.reason}; destination ${input.destination}.`);return event}
export async function completeJobLifecycle(card:DemoJobCard,odometer=0){const batch:TyreLifecycleEvent[]=[];for(const item of card.items.filter(i=>i.approved)){if(item.type!=='Tyre replacement'||!item.position)continue;const oldId=`CURRENT-${card.registration}-${item.position.replace(/\s/g,'-')}`;const removal:TyreLifecycleEvent={id:`REM-${Date.now()}-${batch.length}`,tyreId:oldId,registration:card.registration,position:item.position,type:'Disposal',reason:'Replacement approved on job card',destination:'Recycling',odometer,createdAt:new Date().toISOString(),jobCardId:card.id};batch.push(removal);if(item.sku){try{await reserveTyreStock(item.sku,item.quantity)}catch{addAudit('System','Stock reservation warning','Job card',card.id,`Could not reserve ${item.quantity} × ${item.sku}; external inventory may own stock.`)}}const fit:TyreLifecycleEvent={id:`FIT-${Date.now()}-${batch.length}`,tyreId:`TYR-${Date.now()}-${batch.length}`,registration:card.registration,position:item.position,type:'Fitment',odometer,createdAt:new Date().toISOString(),jobCardId:card.id,sku:item.sku,notes:item.description};batch.push(fit)}if(batch.length)lifecycleStore.saveEvents([...batch,...lifecycleStore.events()]);addAudit('Current technician','Job completed','Job card',card.id,`Lifecycle updated with ${batch.length} removal/fitment events.`);return batch}
export function saveOfflineInspection(draft:Omit<OfflineInspectionDraft,'id'|'updatedAt'|'status'>){const existing=lifecycleStore.offlineDrafts();const online=typeof navigator==='undefined'?true:navigator.onLine;const item:OfflineInspectionDraft={...draft,id:`OFF-${Date.now()}`,updatedAt:new Date().toISOString(),status:online?'Ready to sync':'Offline draft'};lifecycleStore.saveOfflineDrafts([item,...existing]);addAudit('Current technician','Inspection saved offline','Inspection draft',item.id,`${item.registration} saved for later sync.`);return item}
export function syncOfflineDrafts(){const next=lifecycleStore.offlineDrafts().map(d=>({...d,status:'Synced' as const,updatedAt:new Date().toISOString()}));lifecycleStore.saveOfflineDrafts(next);addAudit('System','Offline drafts synced','Offline sync','SYNC',`${next.length} drafts marked synced.`);return next}
export function matchRecall(manufacturer:string,model:string){const matches=tyres.filter(t=>t.brand.toLowerCase().includes(manufacturer.toLowerCase())&&t.model.toLowerCase().includes(model.toLowerCase()));return {affectedTyres:matches.length,matchedVehicles:Array.from(new Set(matches.map(t=>t.vehicle)))} }
export function createRecallCampaign(input:Omit<RecallCampaign,'affectedTyres'|'matchedVehicles'|'createdAt'>){const matches=matchRecall(input.manufacturer,input.model);const item:RecallCampaign={...input,...matches,createdAt:new Date().toISOString()};lifecycleStore.saveRecalls([item,...lifecycleStore.recalls()]);addAudit('Current manager','Recall campaign created','Recall',item.id,`${item.affectedTyres} tyres matched across ${item.matchedVehicles.length} vehicles.`);return item}
export function updateSupplierOrder(id:string,status:SupplierOrder['status'],receiveAll=false){const orders=lifecycleStore.orders();const next=orders.map(o=>o.id===id?{...o,status,items:receiveAll?o.items.map(i=>({...i,received:i.quantity})):o.items}:o);lifecycleStore.saveOrders(next);addAudit('Current manager','Supplier order updated','Supplier order',id,`Order moved to ${status}.`);return next.find(o=>o.id===id)}
