import { useMemo, useState } from 'react';
import { CheckCircle2, FileText, ShieldCheck, XCircle } from 'lucide-react';
import { jobCardSubtotal, jobCardTotal, jobCardVat, workflowStore, type DemoJobCard } from '../../lib/workflowStore';

type Props={customer:string;registration:string;onClose:()=>void;onDecision:(message:string)=>void};
const money=(value:number)=>`R ${value.toLocaleString('en-ZA',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
export function CustomerQuoteApproval({customer,registration,onClose,onDecision}:Props){
 const [version,setVersion]=useState(0);const [note,setNote]=useState('');const cards=workflowStore.jobCards();
 const quotes=useMemo(()=>cards.filter(c=>c.customer===customer&&c.registration===registration&&['Quote sent','Approved','Declined'].includes(c.status)),[cards,customer,registration,version]);
 const pending=quotes.find(c=>c.quoteDecision==='Pending')??quotes[0];
 const decide=(card:DemoJobCard,decision:'Approved'|'Declined')=>{const next={...card,quoteDecision:decision,status:decision,decisionAt:new Date().toISOString(),customerNote:note||undefined} as DemoJobCard;workflowStore.saveJobCards(workflowStore.jobCards().map(c=>c.id===card.id?next:c));setVersion(v=>v+1);onDecision(decision==='Approved'?`Quotation ${card.quoteNumber} approved. The workshop can now schedule the work.`:`Quotation ${card.quoteNumber} declined. The workshop has been notified.`)};
 return <div className="fixed inset-0 z-50 overflow-y-auto bg-black/50 p-4 backdrop-blur-sm"><div className="mx-auto my-8 w-full max-w-3xl rounded-[28px] bg-white p-5 shadow-2xl sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.12em] text-brand-orange">Workshop quotation</p><h2 className="mt-1 text-2xl font-extrabold">Review recommended work</h2><p className="mt-2 text-sm text-zinc-500">Approve the workshop work before technicians begin. You can decline and contact the branch if you want another option.</p></div><button onClick={onClose} className="rounded-xl bg-zinc-100 p-2 text-zinc-500"><XCircle size={19}/></button></div>
 {!pending?<div className="mt-7 rounded-2xl bg-[#F5F4F0] p-8 text-center"><FileText size={28} className="mx-auto text-zinc-300"/><p className="mt-3 text-sm font-bold text-zinc-500">There are no quotations waiting for you.</p></div>:<div className="mt-6"><section className="rounded-2xl bg-[#202124] p-5 text-white"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.12em] text-zinc-400">{pending.quoteNumber}</p><p className="mt-1 text-xl font-extrabold">{pending.registration}</p><p className="mt-1 text-xs text-zinc-400">{pending.branch} · Job {pending.id}</p></div><span className={`rounded-full px-3 py-1.5 text-xs font-bold ${pending.quoteDecision==='Approved'?'bg-emerald-400/15 text-emerald-300':pending.quoteDecision==='Declined'?'bg-red-400/15 text-red-300':'bg-amber-400/15 text-amber-300'}`}>{pending.quoteDecision}</span></div></section>
 <div className="mt-4 divide-y divide-black/[0.05] rounded-2xl border border-black/[0.06] px-4">{pending.items.filter(i=>i.approved).map(item=><div key={item.id} className="flex items-start justify-between gap-4 py-4"><div><p className="text-sm font-extrabold">{item.description}</p><p className="mt-1 text-xs text-zinc-400">{item.type}{item.position?` · ${item.position}`:''}</p></div><p className="shrink-0 text-sm font-extrabold">{money(item.quantity*item.unitPrice)}</p></div>)}</div>
 <div className="mt-4 rounded-2xl bg-[#F7F6F2] p-4 text-sm"><div className="flex justify-between py-1 text-zinc-500"><span>Subtotal</span><span>{money(jobCardSubtotal(pending))}</span></div><div className="flex justify-between py-1 text-zinc-500"><span>VAT ({pending.vatRate}%)</span><span>{money(jobCardVat(pending))}</span></div><div className="mt-2 flex justify-between border-t border-black/[0.06] pt-3 text-lg font-extrabold"><span>Total</span><span>{money(jobCardTotal(pending))}</span></div></div>
 {pending.quoteDecision==='Pending'?<><label className="mt-5 block text-xs font-bold text-zinc-600">Message to workshop (optional)<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Questions, preferred timing, or anything the workshop should know" className="mt-2 min-h-24 w-full rounded-xl border border-black/[0.08] p-3 text-sm outline-none focus:border-orange-300"/></label><div className="mt-4 grid gap-3 sm:grid-cols-2"><button onClick={()=>decide(pending,'Declined')} className="h-12 rounded-xl bg-red-50 text-sm font-extrabold text-red-700">Decline quotation</button><button onClick={()=>decide(pending,'Approved')} className="inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-brand-orange text-sm font-extrabold text-white"><CheckCircle2 size={17}/>Approve {money(jobCardTotal(pending))}</button></div></>:<div className={`mt-5 flex gap-3 rounded-2xl p-4 ${pending.quoteDecision==='Approved'?'bg-emerald-50 text-emerald-800':'bg-red-50 text-red-800'}`}><ShieldCheck size={18}/><div><p className="text-sm font-extrabold">Quotation {pending.quoteDecision.toLowerCase()}</p><p className="mt-1 text-xs leading-5">{pending.quoteDecision==='Approved'?'The workshop is authorised to start the approved work.':'The workshop will not proceed with this quotation unless a new approval is given.'}</p></div></div>}</div>}</div></div>;
}
