import { useMemo, useState } from 'react';
import { ArrowLeft, CalendarPlus, CheckCircle2 } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { PageHeader } from '../components/ui/PageHeader';
import { getNextBookingNumber, workflowStore, type DemoBooking } from '../lib/workflowStore';

export default function BookingCreatePage(){
 const navigate=useNavigate();const customers=workflowStore.customers();const vehicles=workflowStore.vehicles();
 const [customerId,setCustomerId]=useState(customers[0]?.id??'');const [registration,setRegistration]=useState(vehicles.find(v=>v.customerId===customers[0]?.id)?.registration??'');const [service,setService]=useState('Tyre inspection');const [date,setDate]=useState('2026-08-18');const [time,setTime]=useState('09:00');const [error,setError]=useState('');
 const customerVehicles=useMemo(()=>vehicles.filter(v=>v.customerId===customerId),[vehicles,customerId]);
 const changeCustomer=(id:string)=>{setCustomerId(id);setRegistration(vehicles.find(v=>v.customerId===id)?.registration??'')};
 const submit=()=>{const customer=customers.find(c=>c.id===customerId);if(!customer||!registration||!date||!time){setError('Customer, vehicle, date and time are required.');return;}const current=workflowStore.bookings();const item:DemoBooking={id:`BKG-${Date.now()}`,bookingNumber:getNextBookingNumber(current,date),customer:customer.name,registration,service,date,time,status:'Confirmed'};workflowStore.saveBookings([...current,item]);navigate(`/bookings/${item.id}`)};
 return <div className="space-y-6"><PageHeader eyebrow="Workshop schedule" title="New booking" description="Create a tyre-service booking and assign the customer-facing queue number automatically." action={<Link to="/bookings" className="inline-flex h-11 items-center gap-2 rounded-xl bg-white px-4 text-sm font-bold text-zinc-600 ring-1 ring-black/[0.06]"><ArrowLeft size={16}/>Back to bookings</Link>}/><section className="mx-auto max-w-3xl rounded-[26px] bg-white p-6 ring-1 ring-black/[0.045] sm:p-7"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-orange-50 text-brand-orange"><CalendarPlus size={19}/></div><div><h2 className="text-lg font-extrabold text-brand-ink">Booking details</h2><p className="mt-1 text-xs text-zinc-400">The booking number is generated per service date.</p></div></div>{error&&<div className="mt-5 rounded-xl bg-red-50 px-4 py-3 text-sm font-bold text-red-700">{error}</div>}<div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold text-zinc-600">Customer<select value={customerId} onChange={e=>changeCustomer(e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-black/[0.08] px-3 text-sm">{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="text-xs font-bold text-zinc-600">Vehicle<select value={registration} onChange={e=>setRegistration(e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-black/[0.08] px-3 text-sm">{customerVehicles.map(v=><option key={v.id} value={v.registration}>{v.registration} · {v.make} {v.model}</option>)}</select></label><label className="text-xs font-bold text-zinc-600">Service<select value={service} onChange={e=>setService(e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-black/[0.08] px-3 text-sm"><option>Tyre inspection</option><option>Rotation & balancing</option><option>Replacement assessment</option><option>Wheel alignment</option><option>TPMS check</option></select></label><label className="text-xs font-bold text-zinc-600">Date<input type="date" value={date} onChange={e=>setDate(e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-black/[0.08] px-3 text-sm"/></label><label className="text-xs font-bold text-zinc-600">Time<input type="time" value={time} onChange={e=>setTime(e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-black/[0.08] px-3 text-sm"/></label></div><button onClick={submit} className="mt-6 inline-flex h-11 items-center gap-2 rounded-xl bg-brand-orange px-5 text-sm font-extrabold text-white"><CheckCircle2 size={16}/>Create booking</button></section></div>;
}