import { useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, CalendarDays, CarFront, Mail, Phone, Plus, Save, ShieldCheck, Wrench } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { workflowStore, type DemoCustomer } from '../lib/workflowStore';
import { tyres } from '../data/mock';

const inputClass='h-11 w-full rounded-xl border border-black/[0.07] bg-white px-3 text-sm outline-none focus:border-orange-200 focus:ring-4 focus:ring-orange-100/50';
export default function CustomerWorkspacePage(){
  const {customerId}=useParams();const navigate=useNavigate();const creating=customerId==='new';
  const customers=workflowStore.customers();const vehicles=workflowStore.vehicles();const bookings=workflowStore.bookings();
  const base=customers.find(c=>c.id===customerId)??{id:`CUS-${Date.now()}`,name:'',mobile:'',email:'',status:'Active' as const};
  const [form,setForm]=useState<DemoCustomer>(base);const [saved,setSaved]=useState(false);
  const linked=useMemo(()=>vehicles.filter(v=>v.customerId===form.id),[vehicles,form.id]);
  const registrations=useMemo(()=>new Set(linked.map(v=>v.registration)),[linked]);
  const customerBookings=useMemo(()=>bookings.filter(b=>registrations.has(b.registration)).sort((a,b)=>`${b.date}${b.time}`.localeCompare(`${a.date}${a.time}`)),[bookings,registrations]);
  const fittedTyres=useMemo(()=>tyres.filter(t=>registrations.has(t.vehicle)),[registrations]);
  const save=()=>{const next=creating?[...customers,form]:customers.map(c=>c.id===form.id?form:c);workflowStore.saveCustomers(next);if(creating){navigate(`/customers/${form.id}`,{replace:true});return}setSaved(true);setTimeout(()=>setSaved(false),1800)};
  const activeBooking=customerBookings.find(b=>!['Cancelled','Completed'].includes(b.status));

  return <div className="mx-auto max-w-7xl space-y-6">
    <div className="flex items-center justify-between"><Link to="/customers" className="inline-flex items-center gap-2 text-sm font-semibold text-zinc-500 hover:text-brand-ink"><ArrowLeft size={16}/>Customers</Link>{saved&&<span className="text-xs font-bold text-emerald-700">Changes saved</span>}</div>

    <div className="flex flex-col gap-5 xl:grid xl:grid-cols-[minmax(0,1fr)_330px] xl:items-start">
      <div className="space-y-5">
        <section className="overflow-hidden rounded-[26px] bg-[#202124] text-white shadow-[0_18px_45px_rgba(24,24,27,.10)]">
          <div className="flex flex-col gap-5 p-5 sm:p-6 lg:flex-row lg:items-center lg:justify-between">
            <div className="flex min-w-0 items-center gap-4"><div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-brand-orange text-lg font-black text-white shadow-lg shadow-orange-950/20">{form.name?form.name.split(' ').map(n=>n[0]).join('').slice(0,2):'+'}</div><div className="min-w-0"><p className="text-[10px] font-bold uppercase tracking-[0.17em] text-orange-300">Customer garage</p><h1 className="mt-1 truncate text-2xl font-extrabold tracking-tight sm:text-3xl">{creating?'New customer':form.name}</h1>{!creating&&<p className="mt-2 text-sm text-zinc-400">{linked.length} linked vehicle{linked.length===1?'':'s'} · {fittedTyres.length} tracked tyre{fittedTyres.length===1?'':'s'}</p>}</div></div>
            {!creating&&<div className="flex flex-wrap gap-2"><a href={`tel:${form.mobile}`} className="inline-flex h-10 items-center gap-2 rounded-xl bg-white/8 px-3 text-xs font-bold text-white ring-1 ring-white/10 hover:bg-white/12"><Phone size={14}/>Call</a><a href={`mailto:${form.email}`} className="inline-flex h-10 items-center gap-2 rounded-xl bg-white/8 px-3 text-xs font-bold text-white ring-1 ring-white/10 hover:bg-white/12"><Mail size={14}/>Email</a><Link to="/bookings/new" state={{customer:form.name,registration:linked[0]?.registration}} className="inline-flex h-10 items-center gap-2 rounded-xl bg-brand-orange px-3 text-xs font-bold text-white"><CalendarDays size={14}/>Book service</Link></div>}
          </div>
          {!creating&&activeBooking&&<Link to={`/bookings/${activeBooking.id}`} className="flex items-center justify-between gap-4 border-t border-white/8 bg-white/[0.035] px-5 py-3.5 text-sm transition hover:bg-white/[0.055] sm:px-6"><div className="flex min-w-0 items-center gap-3"><CalendarDays size={16} className="shrink-0 text-brand-orange"/><div className="min-w-0"><p className="truncate font-bold">Upcoming: {activeBooking.service}</p><p className="mt-0.5 text-xs text-zinc-400">{activeBooking.date} · {activeBooking.time} · {activeBooking.registration}</p></div></div><ArrowRight size={15} className="shrink-0 text-zinc-500"/></Link>}
        </section>

        <section className="rounded-[24px] bg-white ring-1 ring-black/[0.045]"><div className="flex flex-col gap-3 border-b border-black/[0.05] p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-extrabold text-brand-ink">Vehicles</h2><p className="mt-1 text-xs text-zinc-400">Open a vehicle to continue into mileage, fitted tyres and lifecycle records.</p></div>{!creating&&<Link to={`/vehicles/new?customer=${form.id}`} className="inline-flex h-9 items-center gap-2 rounded-xl bg-orange-50 px-3 text-xs font-bold text-brand-orange"><Plus size={14}/>Add vehicle</Link>}</div><div className="divide-y divide-black/[0.05]">{linked.length?linked.map(v=>{const vehicleTyres=tyres.filter(t=>t.vehicle===v.registration);const attention=vehicleTyres.filter(t=>t.status!=='Good').length;return <Link to={`/vehicles/${v.id}`} key={v.id} className="grid gap-4 p-5 transition hover:bg-[#FAF9F6] sm:grid-cols-[1fr_170px_150px_40px] sm:items-center"><div className="flex min-w-0 items-center gap-3"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-[#F2F1ED] text-zinc-600"><CarFront size={18}/></div><div className="min-w-0"><p className="truncate text-sm font-extrabold text-brand-ink">{v.make} {v.model}</p><p className="mt-1 text-xs text-zinc-400">{v.registration} · {v.year}</p></div></div><div><p className="text-[10px] font-bold uppercase tracking-wider text-zinc-400">Odometer</p><p className="mt-1 text-sm font-bold text-brand-ink">{v.mileage.toLocaleString('en-ZA')} km</p></div><div><p className="text-[10px] font-bold uppercase tracking-wider text-zinc-400">Tyre status</p><p className={`mt-1 text-sm font-bold ${attention?'text-amber-700':'text-emerald-700'}`}>{attention?`${attention} need attention`:`${vehicleTyres.length||4} healthy`}</p></div><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#F5F4F0] text-zinc-400"><ArrowRight size={15}/></div></Link>}):<div className="py-12 text-center"><ShieldCheck size={23} className="mx-auto text-zinc-300"/><p className="mt-2 text-sm font-semibold text-zinc-500">No vehicles linked yet</p><p className="mt-1 text-xs text-zinc-400">Add the customer's first vehicle to begin tyre lifecycle tracking.</p></div>}</div></section>

        {!creating&&<section className="rounded-[24px] bg-white ring-1 ring-black/[0.045]"><div className="border-b border-black/[0.05] p-5"><h2 className="font-extrabold text-brand-ink">Service history</h2><p className="mt-1 text-xs text-zinc-400">Recent bookings and workshop activity for this customer's vehicles.</p></div><div className="divide-y divide-black/[0.05]">{customerBookings.length?customerBookings.slice(0,5).map(b=><Link to={`/bookings/${b.id}`} key={b.id} className="flex items-center justify-between gap-4 px-5 py-4 transition hover:bg-[#FAF9F6]"><div className="flex min-w-0 items-center gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-orange-50 text-brand-orange"><Wrench size={15}/></div><div className="min-w-0"><p className="truncate text-sm font-bold text-brand-ink">{b.service}</p><p className="mt-1 text-xs text-zinc-400">{b.registration} · {b.date} · {b.time}</p></div></div><span className="rounded-full bg-[#F5F4F0] px-2.5 py-1 text-[10px] font-bold text-zinc-600">{b.status}</span></Link>):<p className="px-5 py-10 text-center text-sm text-zinc-400">No service history yet.</p>}</div></section>}
      </div>

      <aside className="rounded-[24px] bg-white p-5 ring-1 ring-black/[0.045] xl:sticky xl:top-24">
        <div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-brand-orange">Customer profile</p><h2 className="mt-1 font-extrabold text-brand-ink">Contact & account</h2></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${form.status==='Active'?'bg-emerald-50 text-emerald-700':'bg-zinc-100 text-zinc-600'}`}>{form.status}</span></div>
        <div className="mt-5 space-y-4"><label className="block text-xs font-bold text-zinc-600">Full name<input className={`mt-2 ${inputClass}`} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="block text-xs font-bold text-zinc-600">Mobile<input className={`mt-2 ${inputClass}`} value={form.mobile} onChange={e=>setForm({...form,mobile:e.target.value})}/></label><label className="block text-xs font-bold text-zinc-600">Email<input className={`mt-2 ${inputClass}`} value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="block text-xs font-bold text-zinc-600">Status<select className={`mt-2 ${inputClass}`} value={form.status} onChange={e=>setForm({...form,status:e.target.value as DemoCustomer['status']})}><option>Active</option><option>Inactive</option></select></label></div>
        <button onClick={save} disabled={!form.name||!form.mobile} className="mt-5 inline-flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-[#202124] px-4 text-sm font-bold text-white transition hover:bg-black disabled:opacity-40"><Save size={16}/>{creating?'Create customer':'Save changes'}</button>
      </aside>
    </div>
  </div>;
}
