import { useMemo, useState } from 'react';
import { ArrowLeft, CarFront, Mail, Phone, Plus, Save, ShieldCheck } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { workflowStore, type DemoCustomer } from '../lib/workflowStore';

const inputClass='h-11 w-full rounded-xl border border-black/[0.07] bg-white px-3 text-sm outline-none focus:border-orange-200 focus:ring-4 focus:ring-orange-100/50';
export default function CustomerWorkspacePage(){
  const { customerId }=useParams();const navigate=useNavigate();const creating=customerId==='new';
  const customers=workflowStore.customers();const vehicles=workflowStore.vehicles();
  const base=customers.find(c=>c.id===customerId)??{id:`CUS-${Date.now()}`,name:'',mobile:'',email:'',status:'Active' as const};
  const [form,setForm]=useState<DemoCustomer>(base);
  const linked=useMemo(()=>vehicles.filter(v=>v.customerId===form.id),[vehicles,form.id]);
  const save=()=>{const next=creating?[...customers,form]:customers.map(c=>c.id===form.id?form:c);workflowStore.saveCustomers(next);navigate('/customers');};
  return <div className="mx-auto max-w-6xl space-y-6"><Link to="/customers" className="inline-flex items-center gap-2 text-sm font-semibold text-zinc-500 hover:text-brand-ink"><ArrowLeft size={16}/>Customers</Link>
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.17em] text-brand-orange">Customer record</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight text-brand-ink">{creating?'Add customer':form.name}</h1><p className="mt-2 text-sm text-zinc-500">Contact details, linked vehicles and service relationship in one working record.</p></div><button onClick={save} disabled={!form.name||!form.mobile} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-[#202124] px-4 text-sm font-bold text-white disabled:opacity-40"><Save size={16}/>{creating?'Create customer':'Save changes'}</button></div>
    <div className="grid gap-5 lg:grid-cols-[0.8fr_1.2fr]"><section className="rounded-[24px] bg-white p-5 ring-1 ring-black/[0.045] sm:p-6"><h2 className="font-extrabold text-brand-ink">Customer details</h2><div className="mt-5 space-y-4"><label className="block text-xs font-bold text-zinc-600">Full name<input className={`mt-2 ${inputClass}`} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="block text-xs font-bold text-zinc-600">Mobile<input className={`mt-2 ${inputClass}`} value={form.mobile} onChange={e=>setForm({...form,mobile:e.target.value})}/></label><label className="block text-xs font-bold text-zinc-600">Email<input className={`mt-2 ${inputClass}`} value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="block text-xs font-bold text-zinc-600">Status<select className={`mt-2 ${inputClass}`} value={form.status} onChange={e=>setForm({...form,status:e.target.value as DemoCustomer['status']})}><option>Active</option><option>Inactive</option></select></label></div>{!creating&&<div className="mt-6 grid grid-cols-2 gap-3"><a href={`tel:${form.mobile}`} className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-[#F5F4F0] text-xs font-bold text-zinc-600"><Phone size={14}/>Call</a><a href={`mailto:${form.email}`} className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-[#F5F4F0] text-xs font-bold text-zinc-600"><Mail size={14}/>Email</a></div>}</section>
      <section className="rounded-[24px] bg-white p-5 ring-1 ring-black/[0.045] sm:p-6"><div className="flex items-center justify-between"><div><h2 className="font-extrabold text-brand-ink">Linked vehicles</h2><p className="mt-1 text-xs text-zinc-400">Vehicles whose tyre records belong to this customer.</p></div>{!creating&&<Link to={`/vehicles/new?customer=${form.id}`} className="inline-flex h-9 items-center gap-2 rounded-xl bg-orange-50 px-3 text-xs font-bold text-brand-orange"><Plus size={14}/>Add vehicle</Link>}</div><div className="mt-5 divide-y divide-black/[0.05]">{linked.length?linked.map(v=><Link to={`/vehicles/${v.id}`} key={v.id} className="flex items-center justify-between gap-4 py-4 first:pt-0 hover:text-brand-orange"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#F2F1ED] text-zinc-600"><CarFront size={17}/></div><div><p className="text-sm font-bold text-brand-ink">{v.make} {v.model}</p><p className="mt-1 text-xs text-zinc-400">{v.registration} · {v.year}</p></div></div><p className="text-xs font-bold text-zinc-500">{v.mileage.toLocaleString('en-ZA')} km</p></Link>):<div className="py-10 text-center"><ShieldCheck size={22} className="mx-auto text-zinc-300"/><p className="mt-2 text-sm font-semibold text-zinc-500">No vehicles linked yet</p></div>}</div></section></div>
  </div>;
}
