import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, CalendarDays, Camera, Car, CheckCircle2, ChevronRight, CircleGauge, FileCheck2, Gauge, LogOut, MapPin, Phone, ShieldCheck, Sparkles, Wrench, X } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { TyreTrackLogo } from '../components/brand/TyreTrackLogo';
import { CustomerTyreInspectionFlow } from '../components/customer/CustomerTyreInspectionFlow';
import { CustomerQuoteApproval } from '../components/customer/CustomerQuoteApproval';
import { addAudit } from '../lib/lifecycleOperations';
import { formatBookingNumber, getNextBookingNumber, workflowStore, type DemoBooking, type DemoVehicle } from '../lib/workflowStore';

type Task='condition'|'mileage'|'booking'|'warranty'|'inspect'|'quotes'|null;
const customer='Thando Mkhize',customerId='CUS-1001';
const primaryTyres=[{position:'Front left',tread:5.2,state:'Good'},{position:'Front right',tread:4.1,state:'Attention'},{position:'Rear left',tread:5.8,state:'Good'},{position:'Rear right',tread:2.1,state:'Critical'}];
const altTyres=[{position:'Front left',tread:6.8,state:'Good'},{position:'Front right',tread:6.7,state:'Good'},{position:'Rear left',tread:6.4,state:'Good'},{position:'Rear right',tread:6.5,state:'Good'}];
export default function CustomerPortalPage(){
 const navigate=useNavigate();const [task,setTask]=useState<Task>(null);const [,setQuoteVersion]=useState(0);const [saved,setSaved]=useState('');const [bookingDate,setBookingDate]=useState('2026-08-20');const [bookingTime,setBookingTime]=useState('09:00');const [vehicleVersion,setVehicleVersion]=useState(0);
 useEffect(()=>{const existing=workflowStore.vehicles();if(!existing.some(v=>v.id==='VEH-2005')){const alt:DemoVehicle={id:'VEH-2005',customerId,registration:'ND 204-765',make:'Volkswagen',model:'T-Roc',year:2024,mileage:18350,status:'Active',branchId:'BR-DBN',fleetId:'FLT-RETAIL'};workflowStore.saveVehicles([...existing,alt]);setVehicleVersion(v=>v+1)}},[]);
 const customerVehicles=useMemo(()=>workflowStore.vehicles().filter(v=>v.customerId===customerId),[vehicleVersion]);const [registration,setRegistration]=useState('ND 452-981');const vehicle=customerVehicles.find(v=>v.registration===registration)??customerVehicles[0];const [mileageDraft,setMileageDraft]=useState(68240);useEffect(()=>{if(vehicle)setMileageDraft(vehicle.mileage)},[vehicle?.id]);
 const tyreSummary=registration==='ND 452-981'?primaryTyres:altTyres;const health=Math.round(tyreSummary.reduce((s,t)=>s+Math.min(100,t.tread/8*100),0)/tyreSummary.length);const pendingQuotes=workflowStore.jobCards().filter(c=>c.customer===customer&&c.registration===registration&&c.status==='Quote sent'&&c.quoteDecision==='Pending');
 const submit=(message:string)=>{setSaved(message);setTask(null);setQuoteVersion(v=>v+1);setTimeout(()=>setSaved(''),5500)};
 const saveMileage=()=>{if(!vehicle)return;workflowStore.saveVehicles(workflowStore.vehicles().map(v=>v.id===vehicle.id?{...v,mileage:mileageDraft}:v));addAudit(customer,'Mileage updated','Vehicle',vehicle.id,`${registration} mileage updated to ${mileageDraft} km from customer portal.`);setVehicleVersion(v=>v+1);submit('Mileage update saved for the selected vehicle.')};
 const requestBooking=()=>{const bookings=workflowStore.bookings();const booking:DemoBooking={id:`BKG-${Date.now()}`,bookingNumber:getNextBookingNumber(bookings,bookingDate),customer,registration,service:'Tyre inspection',date:bookingDate,time:bookingTime,status:'Pending'};workflowStore.saveBookings([...bookings,booking]);addAudit(customer,'Booking requested','Vehicle',registration,`Tyre inspection requested for ${bookingDate} ${bookingTime}.`);submit(`Booking request received. Your booking number is ${formatBookingNumber(booking)}.`)};
 const tasks=[{key:'inspect' as Task,icon:Camera,title:'Inspect my tyres',desc:'Use your phone camera to scan all four tyres',tone:'bg-orange-50 text-brand-orange'},{key:'quotes' as Task,icon:FileCheck2,title:'Quotes & approvals',desc:pendingQuotes.length?`${pendingQuotes.length} quotation waiting`:'Review workshop quotations',tone:'bg-violet-50 text-violet-700'},{key:'condition' as Task,icon:Gauge,title:'Tyre condition',desc:'View verified workshop readings',tone:'bg-emerald-50 text-emerald-700'},{key:'mileage' as Task,icon:CircleGauge,title:'Update mileage',desc:'Keep this vehicle record accurate',tone:'bg-blue-50 text-blue-700'},{key:'booking' as Task,icon:CalendarDays,title:'Book inspection',desc:'Choose a workshop visit',tone:'bg-amber-50 text-amber-700'},{key:'warranty' as Task,icon:ShieldCheck,title:'Warranty',desc:'Check fitted-tyre protection',tone:'bg-zinc-100 text-zinc-700'}];
 return <div className="min-h-screen bg-[#F4F3EF] text-brand-ink"><header className="sticky top-0 z-30 border-b border-black/[0.05] bg-white/95 backdrop-blur"><div className="mx-auto flex h-[72px] max-w-7xl items-center justify-between px-5 sm:px-8"><TyreTrackLogo/><div className="flex items-center gap-3"><div className="hidden text-right sm:block"><p className="text-sm font-extrabold">{customer}</p><p className="text-xs text-zinc-400">Customer account</p></div><button onClick={()=>navigate('/customer-access',{replace:true})} className="inline-flex h-10 items-center gap-2 rounded-xl border border-black/[0.07] bg-white px-3 text-sm font-bold text-zinc-600"><LogOut size={16}/>Sign out</button></div></div></header>
 <main className="mx-auto max-w-7xl px-5 py-7 sm:px-8 sm:py-9">{saved&&<div className="mb-5 flex items-center gap-2 rounded-2xl bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-700"><CheckCircle2 size={17}/>{saved}</div>}
 <section className="mb-5 flex flex-col gap-3 rounded-[22px] bg-white p-4 ring-1 ring-black/[0.05] sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.12em] text-zinc-400">My vehicles</p><p className="mt-1 text-sm font-extrabold">Choose the vehicle you want to manage</p></div><div className="flex flex-wrap gap-2">{customerVehicles.map(v=><button key={v.id} onClick={()=>setRegistration(v.registration)} className={`rounded-xl px-4 py-2.5 text-sm font-bold ${registration===v.registration?'bg-[#202124] text-white':'bg-[#F5F4F0] text-zinc-600'}`}>{v.year} {v.make} {v.model}<span className="ml-2 opacity-60">{v.registration}</span></button>)}</div></section>
 {pendingQuotes.length>0&&<button onClick={()=>setTask('quotes')} className="mb-5 flex w-full items-center justify-between rounded-2xl bg-violet-50 p-4 text-left ring-1 ring-violet-100"><div className="flex items-center gap-3"><FileCheck2 size={20} className="text-violet-700"/><div><p className="text-sm font-extrabold text-violet-900">Quotation waiting for {registration}</p><p className="mt-1 text-xs text-violet-600">Review the recommended work before the workshop starts.</p></div></div><ArrowRight size={17}/></button>}
 <section className="relative overflow-hidden rounded-[30px] bg-[#202124] px-6 py-7 text-white sm:px-8"><div className="absolute -right-16 -top-20 h-72 w-72 rounded-full border-[42px] border-white/[0.035]"/><div className="relative grid gap-7 lg:grid-cols-[1fr_360px] lg:items-center"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.14em] text-orange-300"><Sparkles size={14}/>Your tyre care</div><h1 className="mt-3 max-w-2xl text-[32px] font-extrabold leading-tight sm:text-[40px]">Manage every vehicle from one account.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-zinc-300">The selected vehicle controls camera inspections, mileage, bookings, quotes and tyre-health history.</p><div className="mt-6 flex gap-3"><button onClick={()=>setTask('inspect')} className="inline-flex h-11 items-center gap-2 rounded-xl bg-brand-orange px-4 text-sm font-extrabold"><Camera size={17}/>Inspect {registration}</button><button onClick={()=>setTask(pendingQuotes.length?'quotes':'booking')} className="inline-flex h-11 items-center gap-2 rounded-xl bg-white/10 px-4 text-sm font-bold ring-1 ring-white/10">{pendingQuotes.length?'Review quote':'Book inspection'}<ArrowRight size={16}/></button></div></div><div className="rounded-[24px] bg-white/[0.07] p-5 ring-1 ring-white/10"><p className="text-xs font-bold uppercase tracking-[.12em] text-zinc-400">Verified tyre health</p><p className="mt-2 text-4xl font-extrabold">{health}%</p><div className="mt-4 h-2 overflow-hidden rounded-full bg-white/10"><div className={`h-full rounded-full ${health>75?'bg-emerald-400':'bg-amber-400'}`} style={{width:`${health}%`}}/></div><p className="mt-4 text-sm font-bold">{registration==='ND 452-981'?'Rear-right tyre requires attention':'No immediate tyre action recorded'}</p></div></div></section>
 <div className="mt-6 grid gap-6 lg:grid-cols-[1fr_340px]"><div className="space-y-6"><section className="rounded-[26px] bg-white p-5 ring-1 ring-black/[0.045] sm:p-6"><div className="flex items-center gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-orange-50 text-brand-orange"><Car size={22}/></div><div><p className="text-xs font-bold uppercase tracking-[.12em] text-zinc-400">Selected vehicle</p><h2 className="mt-1 text-lg font-extrabold">{vehicle?.year} {vehicle?.make} {vehicle?.model}</h2><p className="mt-1 text-sm text-zinc-500">{registration} · {(vehicle?.mileage??mileageDraft).toLocaleString('en-ZA')} km</p></div></div><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{tyreSummary.map(t=><button key={t.position} onClick={()=>setTask('condition')} className="rounded-2xl bg-[#F7F6F2] p-4 text-left hover:bg-orange-50"><div className={`mb-5 h-2 w-8 rounded-full ${t.state==='Good'?'bg-emerald-500':t.state==='Critical'?'bg-red-500':'bg-amber-400'}`}/><p className="text-xs font-bold text-zinc-500">{t.position}</p><p className="mt-1 text-xl font-extrabold">{t.tread.toFixed(1)} <span className="text-xs text-zinc-400">mm</span></p><p className="mt-2 text-xs font-bold">{t.state}</p></button>)}</div></section><section><p className="text-xs font-bold uppercase tracking-[.12em] text-zinc-400">Self service</p><h2 className="mt-1 text-lg font-extrabold">What would you like to do?</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{tasks.map(({key,icon:Icon,title,desc,tone})=><button key={String(key)} onClick={()=>setTask(key)} className="flex items-center gap-4 rounded-[22px] bg-white p-5 text-left ring-1 ring-black/[0.045]"><div className={`flex h-11 w-11 items-center justify-center rounded-2xl ${tone}`}><Icon size={20}/></div><div className="flex-1"><p className="text-sm font-extrabold">{title}</p><p className="mt-1 text-xs text-zinc-500">{desc}</p></div><ChevronRight size={17} className="text-zinc-300"/></button>)}</div></section></div>
 <aside className="space-y-4"><section className="rounded-[24px] bg-white p-5 ring-1 ring-black/[0.045]"><p className="text-xs font-bold uppercase tracking-[.12em] text-zinc-400">Selected vehicle action</p><div className="mt-4 flex h-11 w-11 items-center justify-center rounded-2xl bg-orange-50 text-brand-orange"><Wrench size={20}/></div><h3 className="mt-4 text-lg font-extrabold">Keep {registration} current</h3><p className="mt-2 text-sm leading-6 text-zinc-500">Camera checks, mileage and bookings stay separated per vehicle.</p></section><section className="rounded-[24px] bg-[#ECEAE4] p-5"><div className="flex items-center gap-2 text-sm font-extrabold"><MapPin size={17} className="text-brand-orange"/>Durban Central</div><a href="tel:0315550180" className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-zinc-700"><Phone size={15}/>031 555 0180</a></section></aside></div></main>
 {task==='inspect'&&<CustomerTyreInspectionFlow registration={registration} onClose={()=>setTask(null)} onComplete={submit}/>} {task==='quotes'&&<CustomerQuoteApproval customer={customer} registration={registration} onClose={()=>setTask(null)} onDecision={submit}/>} 
 {task&& !['inspect','quotes'].includes(task)&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/45 p-4"><div className="w-full max-w-lg rounded-[26px] bg-white p-5 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-lg font-extrabold">{task==='condition'?'Tyre condition':task==='mileage'?'Update mileage':task==='booking'?'Book tyre inspection':'Warranty & protection'}</h2><button onClick={()=>setTask(null)} className="rounded-xl bg-zinc-100 p-2"><X size={18}/></button></div>{task==='condition'&&<div className="mt-5 space-y-2">{tyreSummary.map(t=><div key={t.position} className="flex justify-between rounded-xl bg-[#F5F4F0] p-4"><div><p className="text-sm font-bold">{t.position}</p><p className="text-xs text-zinc-400">Verified workshop tread</p></div><div className="text-right"><p className="font-extrabold">{t.tread.toFixed(1)} mm</p><p className="text-xs">{t.state}</p></div></div>)}</div>}{task==='mileage'&&<div className="mt-5"><input type="number" value={mileageDraft} onChange={e=>setMileageDraft(Number(e.target.value))} className="h-11 w-full rounded-xl border px-3 text-sm"/><button onClick={saveMileage} className="mt-4 h-11 w-full rounded-xl bg-[#202124] text-sm font-bold text-white">Save mileage for {registration}</button></div>}{task==='booking'&&<div className="mt-5 grid gap-4"><input type="date" value={bookingDate} onChange={e=>setBookingDate(e.target.value)} className="h-11 rounded-xl border px-3 text-sm"/><select value={bookingTime} onChange={e=>setBookingTime(e.target.value)} className="h-11 rounded-xl border px-3 text-sm"><option>09:00</option><option>11:00</option><option>14:00</option></select><button onClick={requestBooking} className="h-11 rounded-xl bg-brand-orange text-sm font-bold text-white">Request booking for {registration}</button></div>}{task==='warranty'&&<div className="mt-5 rounded-xl bg-[#F5F4F0] p-4"><p className="text-sm font-extrabold">Manufacturer warranty status</p><p className="mt-2 text-xs text-zinc-500">Coverage is linked to the fitted tyre passports for {registration}.</p></div>}</div></div>}
 </div>;
}
