import { Activity, BatteryWarning, RadioTower, RefreshCw, Search, Wifi, WifiOff } from 'lucide-react';
import { useMemo, useState } from 'react';
import { PageHeader } from '../components/ui/PageHeader';
import { workflowStore } from '../lib/workflowStore';

export default function DevicesTpmsPage(){
 const [search,setSearch]=useState('');const [version,setVersion]=useState(0);const devices=workflowStore.devices();const tpms=workflowStore.tpms();
 const filtered=useMemo(()=>devices.filter(d=>!search||[d.name,d.type,d.status].some(v=>v.toLowerCase().includes(search.toLowerCase()))),[devices,search,version]);
 const test=(id:string)=>{const next=workflowStore.devices().map(d=>d.id===id?{...d,status:'Connected' as const,lastSync:'Just now'}:d);workflowStore.saveDevices(next);setVersion(v=>v+1)};
 return <div className="space-y-6"><PageHeader eyebrow="Hardware & vehicle telemetry" title="Devices & TPMS" description="See where tyre data came from, monitor connected workshop equipment and review live pressure readings."/>
 <section className="rounded-[24px] bg-white p-5 ring-1 ring-black/[0.05]"><div className="flex items-center gap-3"><RadioTower size={19} className="text-brand-orange"/><div><h2 className="text-lg font-extrabold">Live TPMS readings</h2><p className="mt-1 text-xs text-zinc-400">Vehicle-generated pressure is supporting evidence and does not replace workshop verification.</p></div></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[820px]"><thead><tr><th>Vehicle</th><th>Position</th><th>Pressure</th><th>Temperature</th><th>Sensor battery</th><th>Source</th><th>Status</th></tr></thead><tbody>{tpms.map(r=><tr key={r.id}><td className="font-bold">{r.registration}</td><td>{r.position}</td><td className="font-extrabold">{r.pressurePsi} PSI</td><td>{r.temperatureC??'—'}°C</td><td><span className={`inline-flex items-center gap-1 ${r.sensorBattery==='Low'?'text-amber-700':'text-zinc-600'}`}>{r.sensorBattery==='Low'&&<BatteryWarning size={14}/>} {r.sensorBattery}</span></td><td>{r.source}</td><td><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${r.status==='Normal'?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}>{r.status}</span></td></tr>)}</tbody></table></div></section>
 <section className="overflow-hidden rounded-[24px] bg-white ring-1 ring-black/[0.05]"><div className="flex items-center justify-between gap-3 border-b border-black/[0.05] p-5"><div><h2 className="text-lg font-extrabold">Connected inspection equipment</h2><p className="mt-1 text-xs text-zinc-400">Digital gauges, TPMS readers, scanners and alignment equipment.</p></div><div className="relative w-full max-w-xs"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-zinc-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find device" className="h-10 w-full rounded-xl bg-[#F5F4F0] pl-9 pr-3 text-sm outline-none"/></div></div><div className="divide-y divide-black/[0.05]">{filtered.map(d=><div key={d.id} className="grid gap-4 p-5 md:grid-cols-[1fr_180px_140px] md:items-center"><div className="flex items-center gap-3"><div className={`flex h-11 w-11 items-center justify-center rounded-2xl ${d.status==='Connected'?'bg-emerald-50 text-emerald-700':d.status==='Offline'?'bg-zinc-100 text-zinc-500':'bg-amber-50 text-amber-700'}`}>{d.status==='Offline'?<WifiOff size={19}/>:<Wifi size={19}/>}</div><div><p className="text-sm font-extrabold">{d.name}</p><p className="mt-1 text-xs text-zinc-400">{d.type} · {d.branchId}</p></div></div><div><p className="text-xs font-bold uppercase tracking-[.1em] text-zinc-400">Last sync</p><p className="mt-1 text-sm font-bold">{d.lastSync}</p></div><button onClick={()=>test(d.id)} className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-[#202124] px-3 text-xs font-bold text-white"><RefreshCw size={14}/>{d.status==='Connected'?'Test device':'Reconnect'}</button></div>)}</div></section>
 <div className="flex items-start gap-3 rounded-2xl bg-blue-50 p-4 text-sm text-blue-800"><Activity size={18} className="mt-0.5 shrink-0"/><p>Each inspection can now record <strong>measurement source + device name + TPMS value</strong>, so enterprise users can audit how a tyre reading was obtained.</p></div></div>;
}
