import { Building2, MapPin, Search, Truck, TriangleAlert } from 'lucide-react';
import { useMemo, useState } from 'react';
import { PageHeader } from '../components/ui/PageHeader';
import { workflowStore } from '../lib/workflowStore';

export default function FleetOperationsPage(){
 const [branch,setBranch]=useState('All');const [search,setSearch]=useState('');const branches=workflowStore.branches();const fleets=workflowStore.fleets();
 const filtered=useMemo(()=>fleets.filter(f=>(branch==='All'||f.branchId===branch)&&(!search||[f.name,f.manager,f.id].some(v=>v.toLowerCase().includes(search.toLowerCase())))),[fleets,branch,search]);
 return <div className="space-y-6"><PageHeader eyebrow="Enterprise operations" title="Fleet & branch management" description="Manage tyre risk across fleets, branches, regions and large vehicle populations without turning the Vehicles page into a dashboard."/>
 <section className="overflow-hidden rounded-[24px] bg-white ring-1 ring-black/[0.05]"><div className="border-b border-black/[0.05] p-5"><div className="flex items-center gap-3"><Building2 size={19} className="text-brand-orange"/><div><h2 className="text-lg font-extrabold">Branch structure</h2><p className="mt-1 text-xs text-zinc-400">Company → region → branch → workshop bays → fleets and vehicles.</p></div></div></div><div className="grid gap-3 p-5 md:grid-cols-3">{branches.map(b=><button key={b.id} onClick={()=>setBranch(b.id)} className={`rounded-2xl p-4 text-left ring-1 transition ${branch===b.id?'bg-orange-50 ring-orange-200':'bg-[#F7F6F2] ring-black/[0.04] hover:bg-white'}`}><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-extrabold">{b.name}</p><p className="mt-1 flex items-center gap-1 text-xs text-zinc-500"><MapPin size={12}/>{b.region}</p></div><span className={`h-2.5 w-2.5 rounded-full ${b.status==='Active'?'bg-emerald-500':'bg-amber-400'}`}/></div><div className="mt-4 flex gap-4 text-xs text-zinc-500"><span><strong className="text-brand-ink">{b.vehicles}</strong> vehicles</span><span><strong className="text-brand-ink">{b.workshopBays}</strong> bays</span></div></button>)}</div></section>
 <section className="overflow-hidden rounded-[24px] bg-white ring-1 ring-black/[0.05]"><div className="flex flex-col gap-3 border-b border-black/[0.05] p-5 md:flex-row md:items-center md:justify-between"><div className="flex gap-2"><button onClick={()=>setBranch('All')} className={`rounded-xl px-3 py-2 text-xs font-bold ${branch==='All'?'bg-[#202124] text-white':'bg-[#F5F4F0] text-zinc-600'}`}>All branches</button>{branch!=='All'&&<span className="rounded-xl bg-orange-50 px-3 py-2 text-xs font-bold text-brand-orange">{branches.find(b=>b.id===branch)?.name}</span>}</div><div className="relative w-full max-w-sm"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-zinc-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search fleet or manager" className="h-10 w-full rounded-xl bg-[#F5F4F0] pl-9 pr-3 text-sm outline-none"/></div></div><div className="overflow-x-auto"><table className="w-full min-w-[900px]"><thead><tr><th>Fleet</th><th>Branch</th><th>Vehicles</th><th>Critical tyres</th><th>Attention tyres</th><th>Manager</th><th>Action</th></tr></thead><tbody>{filtered.map(f=><tr key={f.id}><td><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#F0EFEB]"><Truck size={16}/></div><div><p className="font-extrabold">{f.name}</p><p className="text-xs text-zinc-400">{f.id}</p></div></div></td><td>{branches.find(b=>b.id===f.branchId)?.name??f.branchId}</td><td className="font-extrabold">{f.vehicles}</td><td><span className="inline-flex items-center gap-1 rounded-full bg-red-50 px-2.5 py-1 text-xs font-bold text-red-700"><TriangleAlert size={13}/>{f.criticalTyres}</span></td><td><span className="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-bold text-amber-700">{f.attentionTyres}</span></td><td>{f.manager}</td><td><button onClick={()=>alert(`${f.name}: bulk vehicle, tyre-risk and mileage workflows will use this fleet scope.`)} className="text-xs font-bold text-brand-orange">Open fleet</button></td></tr>)}{filtered.length===0&&<tr><td colSpan={7} className="py-12 text-center text-sm text-zinc-400">No fleets match this scope.</td></tr>}</tbody></table></div></section>
 <section className="rounded-[24px] bg-[#202124] p-5 text-white"><h2 className="text-lg font-extrabold">Built for large populations</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-zinc-400">Fleet scoping keeps 2,000+ vehicles manageable. The next backend phase can add bulk mileage import, bulk inspection assignment, depot-level permissions and head-office reporting without changing the frontend structure.</p></section></div>;
}
