import { useMemo, useState } from 'react';
import { ArrowLeft, CheckCircle2, FileText, Play, Send, Wrench } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { completeJobLifecycle, addAudit } from '../lib/lifecycleOperations';
import { jobCardSubtotal, jobCardTotal, jobCardVat, workflowStore, type DemoJobCard, type JobCardStatus } from '../lib/workflowStore';

const money=(value:number)=>`R ${value.toLocaleString('en-ZA',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
export default function JobCardWorkspacePage(){
 const {jobCardId}=useParams();const navigate=useNavigate();const [version,setVersion]=useState(0);const cards=workflowStore.jobCards();const card=useMemo(()=>cards.find(c=>c.id===jobCardId),[cards,jobCardId,version]);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 if(!card)return <div className="rounded-2xl bg-white p-8 text-center"><p className="font-bold">Job card not found.</p><button onClick={()=>navigate('/job-cards')} className="mt-4 text-sm font-bold text-brand-orange">Back to job cards</button></div>;
 const persist=(next:DemoJobCard,msg:string)=>{workflowStore.saveJobCards(workflowStore.jobCards().map(c=>c.id===next.id?next:c));setVersion(v=>v+1);setMessage(msg);setTimeout(()=>setMessage(''),2500)};
 const setStatus=(status:JobCardStatus)=>{persist({...card,status},`Job moved to ${status}.`);addAudit('Current user','Job status changed','Job card',card.id,`Status changed to ${status}.`)};
 const sendQuote=()=>{persist({...card,status:'Quote sent',quoteDecision:'Pending',quoteSentAt:new Date().toISOString()},'Quotation sent to the customer portal.');addAudit('Current user','Quotation sent','Job card',card.id,`Quote ${card.quoteNumber} sent to customer.`)};
 const toggleItem=(id:string)=>{persist({...card,items:card.items.map(i=>i.id===id?{...i,approved:!i.approved}:i)},'Quote line updated.');addAudit('Current user','Quote item changed','Job card',card.id,`Quote item ${id} approval changed.`)};
 const complete=async()=>{if(card.status!=='In workshop'||busy)return;setBusy(true);try{const vehicle=workflowStore.vehicles().find(v=>v.registration===card.registration);await completeJobLifecycle(card,vehicle?.mileage??0);persist({...card,status:'Completed',completedAt:new Date().toISOString()},'Job completed. Stock, removals, fitments and audit history were updated.')}finally{setBusy(false)}};
 return <div className="mx-auto max-w-6xl space-y-6"><div className="flex items-center justify-between"><Link to="/job-cards" className="inline-flex items-center gap-2 text-sm font-bold text-zinc-500"><ArrowLeft size={16}/>Job cards</Link>{message&&<span className="inline-flex items-center gap-2 text-sm font-bold text-emerald-700"><CheckCircle2 size={16}/>{message}</span>}</div>
 <section className="rounded-[26px] bg-[#202124] p-6 text-white sm:p-7"><div className="flex flex-col gap-5 md:flex-row md:items-start md:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-orange-300">{card.id}</p><h1 className="mt-2 text-3xl font-extrabold">{card.customer} · {card.registration}</h1><p className="mt-2 text-sm text-zinc-400">{card.branch} · Quote {card.quoteNumber}</p></div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-white/10 px-3 py-1.5 text-xs font-bold">{card.status}</span><span className={`rounded-full px-3 py-1.5 text-xs font-bold ${card.quoteDecision==='Approved'?'bg-emerald-400/15 text-emerald-300':card.quoteDecision==='Declined'?'bg-red-400/15 text-red-300':'bg-amber-400/15 text-amber-300'}`}>{card.quoteDecision}</span></div></div></section>
 <div className="grid gap-5 lg:grid-cols-[1fr_330px]"><section className="rounded-[24px] bg-white p-5 ring-1 ring-black/[0.05] sm:p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.12em] text-zinc-400">Quotation</p><h2 className="mt-1 text-lg font-extrabold">Recommended work</h2></div><FileText size={20} className="text-brand-orange"/></div><div className="mt-5 divide-y divide-black/[0.05]">{card.items.map(item=><label key={item.id} className="flex cursor-pointer gap-4 py-4"><input type="checkbox" checked={item.approved} onChange={()=>toggleItem(item.id)} className="mt-1 h-4 w-4 accent-orange-500"/><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-extrabold">{item.description}</p><p className="mt-1 text-xs text-zinc-400">{item.type}{item.position?` · ${item.position}`:''}{item.sku?` · ${item.sku}`:''}</p></div><p className="shrink-0 text-sm font-extrabold">{money(item.quantity*item.unitPrice)}</p></div></div></label>)}</div><div className="mt-5 border-t border-black/[0.06] pt-4 text-sm"><div className="flex justify-between py-1.5 text-zinc-500"><span>Subtotal</span><span>{money(jobCardSubtotal(card))}</span></div><div className="flex justify-between py-1.5 text-zinc-500"><span>VAT ({card.vatRate}%)</span><span>{money(jobCardVat(card))}</span></div><div className="mt-2 flex justify-between border-t border-black/[0.06] pt-3 text-lg font-extrabold"><span>Total</span><span>{money(jobCardTotal(card))}</span></div></div></section>
 <aside className="space-y-4"><section className="rounded-[24px] bg-white p-5 ring-1 ring-black/[0.05]"><p className="text-xs font-bold uppercase tracking-[.12em] text-zinc-400">Customer approval</p><p className="mt-2 text-lg font-extrabold">{card.quoteDecision}</p><p className="mt-2 text-xs leading-5 text-zinc-500">The customer sees this quotation in their portal and can approve or decline before work starts.</p>{card.customerNote&&<div className="mt-4 rounded-xl bg-[#F5F4F0] p-3 text-xs leading-5 text-zinc-600">Customer note: {card.customerNote}</div>}<button onClick={sendQuote} className="mt-5 inline-flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-brand-orange text-sm font-bold text-white"><Send size={16}/>{card.quoteSentAt?'Resend quote':'Send quote to customer'}</button></section>
 <section className="rounded-[24px] bg-white p-5 ring-1 ring-black/[0.05]"><p className="text-xs font-bold uppercase tracking-[.12em] text-zinc-400">Workshop progression</p><div className="mt-4 space-y-2"><button disabled={card.quoteDecision!=='Approved'} onClick={()=>setStatus('In workshop')} className="inline-flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-[#202124] text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-35"><Play size={16}/>Start work</button><button disabled={card.status!=='In workshop'||busy} onClick={complete} className="inline-flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-emerald-600 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-35"><CheckCircle2 size={16}/>{busy?'Updating lifecycle...':'Complete job'}</button></div><p className="mt-3 text-xs leading-5 text-zinc-400">Completion records removals and fitments, consumes reserved stock where possible, and writes an audit trail.</p></section><section className="rounded-[24px] bg-orange-50 p-5"><div className="flex gap-3"><Wrench size={18} className="text-brand-orange"/><div><p className="text-sm font-extrabold">Inspection-linked job</p><p className="mt-1 text-xs leading-5 text-zinc-600">Linked inspection records: {card.inspectionIds.join(', ')||'None'}</p></div></div></section></aside></div></div>;
}
