import { useMemo, useState } from 'react';
import { ClipboardList, Search, Wrench } from 'lucide-react';
import { Link } from 'react-router-dom';
import { PageHeader } from '../components/ui/PageHeader';
import { jobCardTotal, workflowStore } from '../lib/workflowStore';

export default function JobCardsPage(){
 const [search,setSearch]=useState('');const cards=workflowStore.jobCards();
 const filtered=useMemo(()=>{const q=search.toLowerCase().trim();return cards.filter(c=>!q||[c.id,c.quoteNumber,c.customer,c.registration,c.status].some(v=>v.toLowerCase().includes(q)))},[cards,search]);
 return <div className="space-y-6"><PageHeader eyebrow="Workshop fulfilment" title="Job cards & quotations" description="Turn inspection findings into approved workshop work, then track the job through completion."/>
 <section className="overflow-hidden rounded-[24px] bg-white ring-1 ring-black/[0.05]"><div className="border-b border-black/[0.05] p-4 sm:p-5"><div className="relative max-w-md"><Search size={16} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-zinc-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search job, quote, customer or vehicle" className="h-11 w-full rounded-xl bg-[#F5F4F0] pl-10 pr-4 text-sm outline-none"/></div></div>
 <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead><tr><th>Job card</th><th>Customer / vehicle</th><th>Quote</th><th>Amount</th><th>Decision</th><th>Status</th><th>Action</th></tr></thead><tbody>{filtered.map(card=><tr key={card.id}><td><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-orange-50 text-brand-orange"><ClipboardList size={17}/></span><div><p className="font-extrabold">{card.id}</p><p className="text-xs text-zinc-400">{new Date(card.createdAt).toLocaleDateString()}</p></div></div></td><td><p className="font-bold">{card.customer}</p><p className="text-xs text-zinc-400">{card.registration} · {card.branch}</p></td><td><p className="font-bold">{card.quoteNumber}</p><p className="text-xs text-zinc-400">{card.items.length} line items</p></td><td className="font-extrabold">R {jobCardTotal(card).toLocaleString('en-ZA',{minimumFractionDigits:2})}</td><td><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${card.quoteDecision==='Approved'?'bg-emerald-50 text-emerald-700':card.quoteDecision==='Declined'?'bg-red-50 text-red-700':'bg-amber-50 text-amber-700'}`}>{card.quoteDecision}</span></td><td><span className="rounded-full bg-[#F5F4F0] px-2.5 py-1 text-xs font-bold text-zinc-700">{card.status}</span></td><td><Link to={`/job-cards/${card.id}`} className="inline-flex items-center gap-1 text-sm font-extrabold text-brand-orange">Open <Wrench size={14}/></Link></td></tr>)}{filtered.length===0&&<tr><td colSpan={7} className="py-12 text-center text-sm text-zinc-400">No job cards match your search.</td></tr>}</tbody></table></div></section></div>;
}
