import { useMemo, useState } from 'react';
import { AlertTriangle, ArrowRightLeft, ClipboardList, History, PackageOpen, Recycle, RefreshCw, RotateCw, Search, Truck } from 'lucide-react';
import { PageHeader } from '../components/ui/PageHeader';
import { addAudit, lifecycleStore, recordRemoval, recordRotation, syncOfflineDrafts, type RecallCampaign, type SupplierOrder } from '../lib/lifecycleOperations';
import { workflowStore } from '../lib/workflowStore';

type Tab='Rotation'|'End of life'|'Recalls'|'Purchasing'|'Audit'|'Offline sync';
const tabs:Tab[]=['Rotation','End of life','Recalls','Purchasing','Audit','Offline sync'];
const input='h-11 w-full rounded-xl border border-black/[0.07] bg-white px-3 text-sm outline-none focus:border-orange-300';
export default function LifecycleOperationsPage(){
 const [tab,setTab]=useState<Tab>('Rotation');const [version,setVersion]=useState(0);const vehicles=workflowStore.vehicles();const [registration,setRegistration]=useState(vehicles[0]?.registration??'');const [odometer,setOdometer]=useState(vehicles[0]?.mileage??0);const [reason,setReason]=useState('Worn below service threshold');const [destination,setDestination]=useState('Recycling');const [position,setPosition]=useState('Rear Right');const [tyreId,setTyreId]=useState('TYR-3004');const [message,setMessage]=useState('');const refresh=(msg:string)=>{setVersion(v=>v+1);setMessage(msg);setTimeout(()=>setMessage(''),2400)};
 const events=lifecycleStore.events(),recalls=lifecycleStore.recalls(),orders=lifecycleStore.orders(),audit=lifecycleStore.audit(),offline=lifecycleStore.offlineDrafts();
 const doRotation=()=>{recordRotation(registration,[{tyreId:'TYR-FL',from:'Front Left',to:'Rear Left'},{tyreId:'TYR-FR',from:'Front Right',to:'Rear Right'},{tyreId:'TYR-RL',from:'Rear Left',to:'Front Left'},{tyreId:'TYR-RR',from:'Rear Right',to:'Front Right'}],odometer);refresh('Rotation event recorded without losing tyre history.')};
 const doRemoval=()=>{recordRemoval({tyreId,registration,position,reason,destination,odometer});refresh('Tyre removal and destination recorded.')};
 const createRecall=()=>{const item:RecallCampaign={id:`RC-${Date.now()}`,manufacturer:'Bridgestone',model:'Turanza',dotRange:'DOT 2026 sample range',severity:'Safety',status:'Active',affectedTyres:0,matchedVehicles:[],action:'Inspect affected batch before further service.',createdAt:new Date().toISOString()};lifecycleStore.saveRecalls([item,...recalls]);addAudit('Current manager','Recall campaign created','Recall',item.id,item.action);refresh('Recall campaign created.')};
 const createOrder=()=>{const item:SupplierOrder={id:`PO-${Date.now()}`,supplier:'Michelin SA',branch:'Durban Central',status:'Draft',createdAt:new Date().toISOString(),expectedDate:'2026-08-22',items:[{sku:'MIC-P4-2055516',description:'Michelin Primacy 4 205/55 R16',quantity:8,unitCost:1710,received:0}]};lifecycleStore.saveOrders([item,...orders]);addAudit('Current manager','Purchase order created','Supplier order',item.id,'Draft replenishment order created.');refresh('Draft purchase order created.')};
 return <div className="space-y-6"><PageHeader eyebrow="Lifecycle control" title="Tyre lifecycle operations" description="Manage rotations, removals, end-of-life destinations, recalls, supplier replenishment, audit history and offline inspection sync."/>{message&&<div className="rounded-xl bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-700">{message}</div>}<div className="flex gap-2 overflow-x-auto rounded-2xl bg-white p-2 ring-1 ring-black/[0.05]">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={`whitespace-nowrap rounded-xl px-4 py-2.5 text-sm font-bold ${tab===t?'bg-[#202124] text-white':'text-zinc-500 hover:bg-[#F5F4F0]'}`}>{t}</button>)}</div>
 {tab==='Rotation'&&<section className="grid gap-5 lg:grid-cols-[1fr_380px]"><div className="rounded-[24px] bg-white p-6 ring-1 ring-black/[0.05]"><div className="flex items-center gap-3"><RotateCw className="text-brand-orange"/><div><h2 className="text-lg font-extrabold">Record tyre rotation</h2><p className="mt-1 text-xs text-zinc-500">The tyre identity stays the same while only its wheel position changes.</p></div></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold text-zinc-600">Vehicle<select className={`mt-2 ${input}`} value={registration} onChange={e=>setRegistration(e.target.value)}>{vehicles.map(v=><option key={v.id}>{v.registration}</option>)}</select></label><label className="text-xs font-bold text-zinc-600">Odometer<input className={`mt-2 ${input}`} type="number" value={odometer} onChange={e=>setOdometer(Number(e.target.value))}/></label></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{[['FL','RL'],['FR','RR'],['RL','FL'],['RR','FR']].map(([from,to])=><div key={from} className="rounded-2xl bg-[#F5F4F0] p-4 text-center"><p className="text-xs font-bold text-zinc-400">{from}</p><ArrowRightLeft size={16} className="mx-auto my-2 text-brand-orange"/><p className="text-sm font-extrabold">{to}</p></div>)}</div><button onClick={doRotation} className="mt-5 h-11 rounded-xl bg-brand-orange px-5 text-sm font-bold text-white">Record rotation</button></div><HistoryList events={events.filter(e=>e.type==='Rotation')}/></section>}
 {tab==='End of life'&&<section className="grid gap-5 lg:grid-cols-[1fr_380px]"><div className="rounded-[24px] bg-white p-6 ring-1 ring-black/[0.05]"><div className="flex items-center gap-3"><Recycle className="text-brand-orange"/><div><h2 className="text-lg font-extrabold">Remove tyre from service</h2><p className="mt-1 text-xs text-zinc-500">Record why the tyre left the vehicle and where it went next.</p></div></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold text-zinc-600">Tyre ID<input value={tyreId} onChange={e=>setTyreId(e.target.value)} className={`mt-2 ${input}`}/></label><label className="text-xs font-bold text-zinc-600">Vehicle<select value={registration} onChange={e=>setRegistration(e.target.value)} className={`mt-2 ${input}`}>{vehicles.map(v=><option key={v.id}>{v.registration}</option>)}</select></label><label className="text-xs font-bold text-zinc-600">Position<select value={position} onChange={e=>setPosition(e.target.value)} className={`mt-2 ${input}`}><option>Front Left</option><option>Front Right</option><option>Rear Left</option><option>Rear Right</option></select></label><label className="text-xs font-bold text-zinc-600">Odometer<input type="number" value={odometer} onChange={e=>setOdometer(Number(e.target.value))} className={`mt-2 ${input}`}/></label><label className="text-xs font-bold text-zinc-600">Removal reason<select value={reason} onChange={e=>setReason(e.target.value)} className={`mt-2 ${input}`}><option>Worn below service threshold</option><option>Puncture damage</option><option>Sidewall damage</option><option>Warranty claim</option><option>Accident damage</option><option>Preventive replacement</option></select></label><label className="text-xs font-bold text-zinc-600">Destination<select value={destination} onChange={e=>setDestination(e.target.value)} className={`mt-2 ${input}`}><option>Recycling</option><option>Retread</option><option>Warranty return</option><option>Stored</option><option>Scrapped</option></select></label></div><button onClick={doRemoval} className="mt-5 h-11 rounded-xl bg-[#202124] px-5 text-sm font-bold text-white">Remove tyre</button></div><HistoryList events={events.filter(e=>e.type!=='Rotation'&&e.type!=='Fitment')}/></section>}
 {tab==='Recalls'&&<section className="rounded-[24px] bg-white ring-1 ring-black/[0.05]"><div className="flex items-center justify-between border-b border-black/[0.05] p-5"><div><h2 className="text-lg font-extrabold">Manufacturer recalls</h2><p className="mt-1 text-xs text-zinc-500">Match affected tyre batches to vehicles and customers.</p></div><button onClick={createRecall} className="rounded-xl bg-[#202124] px-4 py-2.5 text-sm font-bold text-white">New recall</button></div><div className="divide-y divide-black/[0.05]">{recalls.map(r=><div key={r.id} className="grid gap-4 p-5 md:grid-cols-[1fr_140px_1fr]"><div><div className="flex items-center gap-2"><AlertTriangle size={17} className="text-brand-orange"/><p className="font-extrabold">{r.manufacturer} {r.model}</p></div><p className="mt-1 text-xs text-zinc-400">{r.id} · {r.dotRange}</p></div><div><p className="text-xs text-zinc-400">Affected</p><p className="mt-1 font-extrabold">{r.affectedTyres} tyres</p></div><div><p className="text-sm font-bold">{r.action}</p><p className="mt-1 text-xs text-zinc-400">Matched vehicles: {r.matchedVehicles.join(', ')||'None yet'}</p></div></div>)}</div></section>}
 {tab==='Purchasing'&&<section className="rounded-[24px] bg-white ring-1 ring-black/[0.05]"><div className="flex items-center justify-between border-b border-black/[0.05] p-5"><div><h2 className="text-lg font-extrabold">Supplier purchasing & replenishment</h2><p className="mt-1 text-xs text-zinc-500">Create POs, track receiving and support branch stock replenishment.</p></div><button onClick={createOrder} className="rounded-xl bg-brand-orange px-4 py-2.5 text-sm font-bold text-white">Create PO</button></div><div className="divide-y divide-black/[0.05]">{orders.map(o=><div key={o.id} className="grid gap-4 p-5 lg:grid-cols-[160px_1fr_180px_160px]"><div><p className="font-extrabold">{o.id}</p><p className="text-xs text-zinc-400">{o.status}</p></div><div><p className="font-bold">{o.supplier}</p><p className="mt-1 text-xs text-zinc-400">{o.items.map(i=>`${i.quantity} × ${i.description}`).join(', ')}</p></div><div><p className="text-xs text-zinc-400">Branch</p><p className="font-bold">{o.branch}</p></div><div><p className="text-xs text-zinc-400">Expected</p><p className="font-bold">{o.expectedDate}</p></div></div>)}</div></section>}
 {tab==='Audit'&&<section className="rounded-[24px] bg-white ring-1 ring-black/[0.05]"><div className="border-b border-black/[0.05] p-5"><h2 className="text-lg font-extrabold">Immutable-style audit history</h2><p className="mt-1 text-xs text-zinc-500">Frontend prototype of who changed what, when and why. Backend audit storage must be append-only.</p></div><div className="divide-y divide-black/[0.05]">{audit.map(a=><div key={a.id} className="grid gap-3 p-5 md:grid-cols-[190px_180px_1fr]"><div><p className="text-sm font-bold">{new Date(a.at).toLocaleString()}</p><p className="text-xs text-zinc-400">{a.actor}</p></div><div><p className="text-sm font-extrabold">{a.action}</p><p className="text-xs text-zinc-400">{a.entityType} · {a.entityId}</p></div><p className="text-sm text-zinc-600">{a.details}</p></div>)}</div></section>}
 {tab==='Offline sync'&&<section className="rounded-[24px] bg-white p-6 ring-1 ring-black/[0.05]"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><RefreshCw className="text-brand-orange"/><div><h2 className="text-lg font-extrabold">Offline inspection queue</h2><p className="mt-1 text-xs text-zinc-500">Technicians can save inspections locally and sync when connectivity returns.</p></div></div><button onClick={()=>{syncOfflineDrafts();refresh('Offline drafts marked as synced.')}} className="h-11 rounded-xl bg-[#202124] px-4 text-sm font-bold text-white">Sync now</button></div><div className="mt-5 divide-y divide-black/[0.05] border-y border-black/[0.05]">{offline.length?offline.map(d=><div key={d.id} className="flex items-center justify-between gap-4 py-4"><div><p className="text-sm font-extrabold">{d.registration}</p><p className="mt-1 text-xs text-zinc-400">{d.id} · {new Date(d.updatedAt).toLocaleString()}</p></div><span className="rounded-full bg-[#F5F4F0] px-3 py-1.5 text-xs font-bold">{d.status}</span></div>):<div className="py-10 text-center text-sm text-zinc-400">No offline inspection drafts.</div>}</div></section>}
 </div>;
}
function HistoryList({events}:{events:ReturnType<typeof lifecycleStore.events>}){return <aside className="rounded-[24px] bg-[#202124] p-5 text-white"><div className="flex items-center gap-2"><History size={18} className="text-orange-300"/><h3 className="font-extrabold">Recent lifecycle events</h3></div><div className="mt-4 space-y-3">{events.slice(0,6).map(e=><div key={e.id} className="rounded-xl bg-white/[0.06] p-3"><p className="text-sm font-bold">{e.type} · {e.tyreId}</p><p className="mt-1 text-xs text-zinc-400">{e.registration}{e.position?` · ${e.position}`:''}</p><p className="mt-1 text-xs text-zinc-500">{e.reason??e.notes??'Lifecycle event recorded'}</p></div>)}{!events.length&&<p className="text-xs text-zinc-500">No events yet.</p>}</div></aside>}
