import { useMemo, useState } from 'react';
import { ArrowRight, CheckCircle2, Filter, Gauge, Search, ShieldCheck, TriangleAlert, X } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { PageHeader } from '../components/ui/PageHeader';
import { evaluateTyreHealth } from '../lib/tyreHealthEngine';

const healthSources = [
  { id:'TY-1003', customer:'Sibusiso Dlamini', vehicle:'2020 VW Polo • ND 186-442', measuredTreadMm:2.1, measuredAt:'14 Aug 2026', abnormalWear:true },
  { id:'TY-1001', customer:'Thando Mkhize', vehicle:'2021 Toyota Corolla • ND 452-871', previousTreadMm:4.2, previousTreadOdometerKm:28000, currentOdometerKm:37200 },
  { id:'TY-1004', customer:'Lerato Molefe', vehicle:'2022 Hyundai i20 • ND 718-235', previousTreadMm:5.1, previousTreadOdometerKm:41000, currentOdometerKm:49800, mileageStale:true },
  { id:'TY-1008', customer:'Ayanda Zulu', vehicle:'2023 Toyota Hilux • ND 931-556', measuredTreadMm:5.6, measuredAt:'12 Aug 2026', rotationKmSince:12400 },
];
const healthCases = healthSources.map(source => ({ ...source, health: evaluateTyreHealth(source) }));
const statusStyles:Record<string,string>={Critical:'bg-red-50 text-red-700 ring-red-100',Attention:'bg-amber-50 text-amber-700 ring-amber-100',Healthy:'bg-emerald-50 text-emerald-700 ring-emerald-100',Unknown:'bg-zinc-100 text-zinc-600 ring-zinc-200'};
const confidenceStyles:Record<string,string>={High:'bg-emerald-50 text-emerald-700',Medium:'bg-amber-50 text-amber-700',Low:'bg-zinc-100 text-zinc-600'};

export default function LifecycleCentrePage(){
 const navigate=useNavigate(); const [search,setSearch]=useState(''); const [action,setAction]=useState('All actions'); const [status,setStatus]=useState('All'); const [showFilters,setShowFilters]=useState(false);
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return healthCases.filter(item=>{const r=item.health;return(!q||[item.customer,item.vehicle,item.id,r.action,r.reason].some(v=>v.toLowerCase().includes(q)))&&(action==='All actions'||r.action.toLowerCase().includes(action.toLowerCase()))&&(status==='All'||r.status===status)})},[search,action,status]);
 const critical=healthCases.filter(i=>i.health.status==='Critical').length, attention=healthCases.filter(i=>i.health.status==='Attention').length, healthy=healthCases.filter(i=>i.health.status==='Healthy').length, verified=healthCases.filter(i=>i.health.evidence==='Measured').length;
 return <div className="space-y-5">
  <PageHeader eyebrow="Tyre intelligence" title="Tyre Health Centre" description="See tyre condition, evidence quality and the next action without turning this page into another dashboard." />
  <section className="relative overflow-hidden rounded-[28px] bg-[#17181A] text-white shadow-[0_18px_45px_rgba(24,24,27,.10)]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_20%,rgba(249,115,22,.18),transparent_34%)]"/><div className="relative grid min-h-[250px] lg:grid-cols-[1.05fr_.95fr]">
   <div className="flex flex-col justify-center px-6 py-8 sm:px-8 lg:px-10"><div className="inline-flex w-fit items-center gap-2 rounded-full border border-white/10 bg-white/[.06] px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.16em] text-zinc-300"><Gauge size={13} className="text-brand-orange"/>Condition intelligence</div><h2 className="mt-5 max-w-xl text-[30px] font-extrabold leading-[1.08] tracking-[-.04em] sm:text-[38px]">Know which tyres are safe.<br/><span className="text-brand-orange">Act before they become a problem.</span></h2><p className="mt-4 max-w-xl text-sm leading-6 text-zinc-400">Measured tread, mileage history and wear signals are combined into one clear health decision.</p><div className="mt-6 flex flex-wrap gap-2.5"><Link to="/inspections" className="inline-flex h-10 items-center gap-2 rounded-xl bg-brand-orange px-4 text-sm font-bold text-white">Start inspection <ArrowRight size={15}/></Link><Link to="/scan-review" className="inline-flex h-10 items-center gap-2 rounded-xl border border-white/15 bg-white/[.06] px-4 text-sm font-semibold text-white">Review scans</Link></div></div>
   <div className="relative hidden min-h-[250px] overflow-hidden lg:block"><img src="https://unsplash.com/photos/GAh_vhU_K5E/download?force=true&w=1400" alt="Tyre tread" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-[#17181A] via-[#17181A]/25 to-transparent"/><div className="absolute bottom-6 right-6 w-[230px] rounded-2xl border border-white/15 bg-black/45 p-4 backdrop-blur-md"><div className="flex items-center justify-between"><span className="inline-flex items-center gap-2 text-xs font-bold text-emerald-300"><CheckCircle2 size={14}/>Healthy tread</span><span className="text-xs text-zinc-300">Measured</span></div><div className="mt-3 flex items-end justify-between"><p className="text-3xl font-extrabold">5.8 <span className="text-sm font-semibold text-zinc-400">mm</span></p><ShieldCheck size={20} className="text-emerald-400"/></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/15"><div className="h-full w-[82%] rounded-full bg-emerald-400"/></div></div></div>
  </div></section>
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
   <div className="rounded-[18px] border border-red-100 bg-gradient-to-br from-red-50 to-white p-4"><p className="text-[10px] font-black uppercase tracking-[.12em] text-red-500">Critical</p><div className="mt-2 flex items-end justify-between"><p className="text-3xl font-extrabold text-red-700">{critical}</p><TriangleAlert size={19} className="text-red-500"/></div><p className="mt-2 text-xs text-red-600/70">Immediate intervention</p></div>
   <div className="rounded-[18px] border border-amber-100 bg-gradient-to-br from-amber-50 to-white p-4"><p className="text-[10px] font-black uppercase tracking-[.12em] text-amber-600">Attention</p><div className="mt-2 flex items-end justify-between"><p className="text-3xl font-extrabold text-amber-800">{attention}</p><Gauge size={19} className="text-amber-500"/></div><p className="mt-2 text-xs text-amber-700/70">Monitor or inspect</p></div>
   <div className="rounded-[18px] border border-emerald-100 bg-gradient-to-br from-emerald-50 to-white p-4"><p className="text-[10px] font-black uppercase tracking-[.12em] text-emerald-600">Healthy</p><div className="mt-2 flex items-end justify-between"><p className="text-3xl font-extrabold text-emerald-800">{healthy}</p><ShieldCheck size={19} className="text-emerald-500"/></div><p className="mt-2 text-xs text-emerald-700/70">No immediate action</p></div>
   <div className="rounded-[18px] border border-orange-100 bg-gradient-to-br from-orange-50 to-white p-4"><p className="text-[10px] font-black uppercase tracking-[.12em] text-brand-orange">Measured evidence</p><div className="mt-2 flex items-end justify-between"><p className="text-3xl font-extrabold text-brand-ink">{verified}</p><CheckCircle2 size={19} className="text-brand-orange"/></div><p className="mt-2 text-xs text-zinc-500">Verified readings</p></div>
  </section>
  <section className="overflow-hidden rounded-[22px] border border-black/[.05] bg-white shadow-[0_8px_24px_rgba(24,24,27,.035)]">
   <div className="border-b border-black/[.05] bg-[#FAF9F6] p-4 sm:p-5"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-base font-extrabold text-brand-ink">Tyre condition queue</h2><p className="mt-1 text-xs text-zinc-400">Prioritised health records and recommended action.</p></div><div className="flex flex-1 flex-wrap justify-end gap-2 lg:max-w-[720px]"><div className="relative min-w-[240px] flex-1"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-zinc-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search customer, vehicle or tyre" className="h-10 w-full rounded-xl border border-black/[.05] bg-white pl-9 pr-3 text-xs outline-none focus:ring-2 focus:ring-orange-100"/></div><select value={action} onChange={e=>setAction(e.target.value)} className="h-10 rounded-xl border border-black/[.05] bg-white px-3 text-xs font-bold text-zinc-600"><option>All actions</option><option>Replacement</option><option>Inspection</option><option>Rotation</option><option>Monitor</option></select><button onClick={()=>setShowFilters(v=>!v)} className={`inline-flex h-10 items-center gap-2 rounded-xl px-3 text-xs font-bold ${showFilters||status!=='All'?'bg-[#202124] text-white':'bg-white text-zinc-600 ring-1 ring-black/[.05]'}`}><Filter size={14}/>Health</button></div></div>{showFilters&&<div className="mt-4 flex flex-wrap items-center gap-2 border-t border-black/[.05] pt-4">{['All','Critical','Attention','Healthy','Unknown'].map(v=><button key={v} onClick={()=>setStatus(v)} className={`rounded-full px-3 py-1.5 text-[11px] font-bold ${status===v?'bg-brand-orange text-white':'bg-white text-zinc-600 ring-1 ring-black/[.06]'}`}>{v}</button>)}{(status!=='All'||action!=='All actions'||search)&&<button onClick={()=>{setStatus('All');setAction('All actions');setSearch('')}} className="ml-auto inline-flex items-center gap-1 text-xs font-bold text-zinc-400"><X size={13}/>Clear</button>}</div>}</div>
   <div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[980px] text-left"><thead><tr className="bg-[#202124] text-[9px] font-bold uppercase tracking-[.15em] text-zinc-300"><th className="px-5 py-3.5">Customer / vehicle</th><th className="px-4 py-3.5">Health</th><th className="px-4 py-3.5">Tread evidence</th><th className="px-4 py-3.5">Confidence</th><th className="px-4 py-3.5">Reason</th><th className="px-4 py-3.5">Next action</th></tr></thead><tbody className="divide-y divide-black/[.05]">{filtered.map(item=>{const r=item.health;return <tr key={item.id} onClick={()=>navigate(`/tyres/${item.id}`)} className="cursor-pointer transition hover:bg-orange-50/35"><td className="px-5 py-4"><p className="text-[13px] font-extrabold text-brand-ink">{item.customer}</p><p className="mt-1 text-[11px] text-zinc-400">{item.vehicle}</p><p className="mt-1 text-[10px] font-bold text-zinc-300">{item.id}</p></td><td className="px-4 py-4"><span className={`inline-flex rounded-full px-2.5 py-1 text-[10px] font-black ring-1 ${statusStyles[r.status]||statusStyles.Unknown}`}>{r.status}</span></td><td className="px-4 py-4"><p className="text-[13px] font-extrabold text-brand-ink">{r.treadLabel}</p><p className="mt-1 text-[10px] text-zinc-400">{r.evidence}{r.evidence==='Measured'&&item.measuredAt?` · ${item.measuredAt}`:''}</p></td><td className="px-4 py-4"><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${confidenceStyles[r.confidence]||confidenceStyles.Low}`}>{r.confidence}</span></td><td className="max-w-[300px] px-4 py-4 text-[11px] leading-5 text-zinc-500">{r.reason}</td><td className="px-4 py-4"><p className="text-[12px] font-extrabold text-brand-ink">{r.action}</p><p className="mt-1 text-[10px] text-brand-orange">Open tyre <ArrowRight size={10} className="inline"/></p></td></tr>})}{filtered.length===0&&<tr><td colSpan={6} className="px-5 py-12 text-center text-sm text-zinc-400">No tyre-health records match these filters.</td></tr>}</tbody></table></div>
   <div className="divide-y divide-black/[.05] md:hidden">{filtered.map(item=>{const r=item.health;return <button key={item.id} onClick={()=>navigate(`/tyres/${item.id}`)} className="w-full p-4 text-left hover:bg-orange-50/30"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-extrabold text-brand-ink">{item.customer}</p><p className="mt-1 text-xs text-zinc-400">{item.vehicle}</p></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ring-1 ${statusStyles[r.status]||statusStyles.Unknown}`}>{r.status}</span></div><div className="mt-4 grid grid-cols-2 gap-3"><div><p className="text-[9px] font-bold uppercase tracking-wider text-zinc-400">Tread</p><p className="mt-1 text-sm font-extrabold">{r.treadLabel}</p></div><div><p className="text-[9px] font-bold uppercase tracking-wider text-zinc-400">Confidence</p><p className="mt-1 text-sm font-extrabold">{r.confidence}</p></div></div><div className="mt-3 rounded-xl bg-[#F7F6F2] p-3"><p className="text-[10px] leading-4 text-zinc-500">{r.reason}</p><p className="mt-2 text-xs font-extrabold text-brand-orange">{r.action}</p></div></button>})}</div>
  </section>
 </div>;
}
