import { BarChart3, Download, FileText, Search } from 'lucide-react';
import { useMemo, useState } from 'react';
import { PageHeader } from '../components/ui/PageHeader';
const reports=[
 {title:'Tyre health distribution',description:'Active tyres grouped by latest recorded condition',category:'Tyre health',updated:'Updated today',bars:[['Good',73,'bg-emerald-500'],['Attention',19,'bg-amber-500'],['Critical',6,'bg-red-500'],['Unknown',2,'bg-zinc-400']]},
 {title:'Customer retention',description:'Repeat visits, reminder response and return-to-branch activity',category:'Customers',updated:'Updated today',bars:[['Returned',64,'bg-emerald-500'],['Reminder response',21,'bg-amber-500'],['Inactive',15,'bg-zinc-400']]},
 {title:'Tyre replacement history',description:'Mileage, age and tread at recorded replacement',category:'Lifecycle',updated:'Updated yesterday',bars:[['Wear limit',52,'bg-red-500'],['Damage',27,'bg-amber-500'],['Age',14,'bg-zinc-400'],['Other',7,'bg-zinc-300']]},
 {title:'Workshop inspection activity',description:'Completed inspections, technician activity and evidence capture',category:'Operations',updated:'Updated today',bars:[['Completed',78,'bg-emerald-500'],['In progress',14,'bg-amber-500'],['Awaiting',8,'bg-zinc-400']]},
];
export default function ReportsPage(){
 const [selectedTitle,setSelectedTitle]=useState(reports[0].title);const [search,setSearch]=useState('');const [branch,setBranch]=useState('All branches');
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return q?reports.filter(r=>[r.title,r.description,r.category].some(v=>v.toLowerCase().includes(q))):reports},[search]);
 const selected=reports.find(r=>r.title===selectedTitle)??reports[0];
 const exportReport=()=>{const csv=['Metric,Value',...selected.bars.map(([label,value])=>`${label},${value}%`)].join('\n');const blob=new Blob([csv],{type:'text/csv'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${selected.title.toLowerCase().replace(/[^a-z0-9]+/g,'-')}.csv`;a.click();URL.revokeObjectURL(url)};
 return <div className="space-y-7"><PageHeader eyebrow="Business intelligence" title="Reports & analytics" description="Open a specific report, apply a period or branch filter, then export the result."/>
<section className="grid min-h-[560px] overflow-hidden rounded-[26px] bg-white ring-1 ring-black/[0.045] xl:grid-cols-[360px_1fr]"><div className="border-b border-black/[0.05] xl:border-b-0 xl:border-r"><div className="p-4"><div className="relative"><Search size={16} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-zinc-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find a report" className="h-11 w-full rounded-xl bg-[#F5F4F0] pl-10 pr-4 text-sm outline-none focus:bg-white focus:ring-2 focus:ring-orange-100"/></div></div><div className="divide-y divide-black/[0.045]">{filtered.map(report=><button onClick={()=>setSelectedTitle(report.title)} key={report.title} className={`w-full p-4 text-left transition hover:bg-[#FBFAF7] ${selected.title===report.title?'bg-orange-50/40':''}`}><div className="flex gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-[#F0EFEB] text-zinc-700"><FileText size={16}/></div><div><p className="text-sm font-black text-brand-ink">{report.title}</p><p className="mt-1 text-[11px] leading-5 text-zinc-500">{report.description}</p><p className="mt-2 text-[10px] font-bold text-zinc-400">{report.category} · {report.updated}</p></div></div></button>)}</div></div><div className="flex flex-col"><div className="flex flex-col gap-4 border-b border-black/[0.05] p-5 sm:flex-row sm:items-end sm:justify-between sm:p-6"><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-zinc-400">Report preview</p><h2 className="mt-2 text-xl font-black text-brand-ink">{selected.title}</h2><p className="mt-1 text-xs text-zinc-500">{selected.description}.</p></div><div className="flex gap-2"><select value={branch} onChange={e=>setBranch(e.target.value)} className="h-10 rounded-xl bg-[#F5F4F0] px-3 text-xs font-bold text-zinc-600 outline-none"><option>All branches</option><option>Durban Central</option><option>Pinetown</option></select><button onClick={exportReport} className="inline-flex h-10 items-center gap-2 rounded-xl bg-[#202124] px-3 text-xs font-bold text-white"><Download size={14}/>Export</button></div></div><div className="flex-1 p-5 sm:p-6"><div className="flex items-center gap-2 text-sm font-black text-brand-ink"><BarChart3 size={17} className="text-brand-orange"/>{branch} breakdown</div><div className="mt-8 space-y-6">{selected.bars.map(([label,value,color])=><div key={String(label)}><div className="mb-2 flex items-center justify-between text-sm"><span className="font-bold text-brand-ink">{String(label)}</span><span className="font-semibold text-zinc-400">{String(value)}%</span></div><div className="h-3 overflow-hidden rounded-full bg-[#F0EFEB]"><div className={`h-full rounded-full ${String(color)}`} style={{width:`${value}%`}}/></div></div>)}</div></div></div></section></div>}
