import { useMemo, useState } from 'react';
import { CheckCircle2, Image, RefreshCw, Search, ShieldAlert, Wrench } from 'lucide-react';
import { PageHeader } from '../components/ui/PageHeader';
import { workflowStore, type DemoTyreScan } from '../lib/workflowStore';

export default function ScanReviewPage(){
 const [version,setVersion]=useState(0);const [search,setSearch]=useState('');const scans=workflowStore.tyreScans();
 const queue=useMemo(()=>scans.filter(s=>(s.submittedBy??(s.recommendation.startsWith('Customer self-service')?'Customer':'Technician'))==='Customer'&&(s.reviewStatus??'Awaiting review')!=='Confirmed').filter(s=>!search||[s.registration,s.position,s.tyreId,s.fileName].some(v=>v.toLowerCase().includes(search.toLowerCase()))),[scans,search,version]);
 const update=(scan:DemoTyreScan,status:NonNullable<DemoTyreScan['reviewStatus']>)=>{const next=workflowStore.tyreScans().map(s=>s.id===scan.id?{...s,reviewStatus:status,verification:status==='Confirmed'?'Technician confirmed':'Pending technician review'} as DemoTyreScan:s);workflowStore.saveTyreScans(next);setVersion(v=>v+1)};
 return <div className="space-y-6"><PageHeader eyebrow="Customer evidence" title="Scan review queue" description="Review camera scans submitted by customers before they influence workshop decisions."/><section className="overflow-hidden rounded-[24px] bg-white ring-1 ring-black/[0.05]"><div className="border-b border-black/[0.05] p-4 sm:p-5"><div className="relative max-w-md"><Search size={16} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-zinc-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search vehicle, tyre or file" className="h-11 w-full rounded-xl bg-[#F5F4F0] pl-10 pr-4 text-sm outline-none"/></div></div><div className="divide-y divide-black/[0.05]">{queue.map(scan=><div key={scan.id} className="grid gap-4 p-5 lg:grid-cols-[1fr_200px_320px] lg:items-center"><div className="flex gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-orange-50 text-brand-orange"><Image size={20}/></div><div><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-extrabold text-brand-ink">{scan.registration} · {scan.position}</p><span className="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-bold text-amber-700">Awaiting review</span></div><p className="mt-1 text-xs text-zinc-400">{scan.tyreId} · {scan.fileName}</p><p className="mt-2 text-sm text-zinc-600">Estimated tread {scan.estimatedTreadMm?.toFixed(1)??'—'} mm · {scan.wearPattern} · {scan.confidence}% confidence</p><p className="mt-1 text-xs leading-5 text-zinc-500">{scan.recommendation}</p></div></div><div><p className="text-xs font-bold uppercase tracking-[.12em] text-zinc-400">Captured</p><p className="mt-1 text-sm font-bold">{new Date(scan.capturedAt).toLocaleString()}</p><p className="mt-2 text-xs text-zinc-400">Customer self-service camera</p></div><div className="flex flex-wrap gap-2 lg:justify-end"><button onClick={()=>update(scan,'Confirmed')} className="inline-flex h-10 items-center gap-2 rounded-xl bg-emerald-50 px-3 text-xs font-bold text-emerald-700"><CheckCircle2 size={15}/>Confirm evidence</button><button onClick={()=>update(scan,'Retake requested')} className="inline-flex h-10 items-center gap-2 rounded-xl bg-[#F5F4F0] px-3 text-xs font-bold text-zinc-600"><RefreshCw size={15}/>Request retake</button><button onClick={()=>update(scan,'Workshop inspection required')} className="inline-flex h-10 items-center gap-2 rounded-xl bg-orange-50 px-3 text-xs font-bold text-brand-orange"><Wrench size={15}/>Workshop check</button></div></div>)}{queue.length===0&&<div className="py-16 text-center"><ShieldAlert size={28} className="mx-auto text-zinc-300"/><p className="mt-3 text-sm font-bold text-zinc-500">No customer scans are waiting for review.</p></div>}</div></section></div>;
}
