import { useState } from 'react';
import { BellRing, Building2, Save, ShieldCheck, Users } from 'lucide-react';
import { PageHeader } from '../components/ui/PageHeader';
const inputClass='h-10 rounded-xl border border-black/[0.07] bg-white px-3 text-sm outline-none focus:border-orange-200 focus:ring-4 focus:ring-orange-100/50';
export default function SettingsPage(){
 const [criticalCooldown,setCriticalCooldown]=useState(48);const [attentionCooldown,setAttentionCooldown]=useState(7);const [maxReminders,setMaxReminders]=useState(2);const [quietStart,setQuietStart]=useState('20:00');const [quietEnd,setQuietEnd]=useState('07:00');const [criticalTread,setCriticalTread]=useState(2.2);const [attentionTread,setAttentionTread]=useState(3.5);const [saved,setSaved]=useState(false);
 const save=()=>{localStorage.setItem('tyretrack.demo.settings',JSON.stringify({criticalCooldown,attentionCooldown,maxReminders,quietStart,quietEnd,criticalTread,attentionTread}));setSaved(true);setTimeout(()=>setSaved(false),2000)};
 return <div className="space-y-6"><PageHeader eyebrow="System administration" title="Settings" description="Configure operational rules used across TyreTrack." action={<button onClick={save} className="inline-flex h-11 items-center gap-2 rounded-xl bg-[#202124] px-4 text-sm font-bold text-white"><Save size={16}/>Save settings</button>}/>{saved&&<div className="rounded-xl bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-700">Settings saved for this frontend prototype.</div>}
 <section className="overflow-hidden rounded-[24px] bg-white ring-1 ring-black/[0.045]"><div className="grid lg:grid-cols-[250px_1fr]"><div className="border-b border-black/[0.05] p-5 lg:border-b-0 lg:border-r"><div className="space-y-2">{[[Building2,'Organisation'],[Users,'Users & roles'],[ShieldCheck,'Tyre rules'],[BellRing,'Notifications']].map(([Icon,label],i)=>{const I=Icon as typeof Building2;return <button key={String(label)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold ${i===2?'bg-orange-50 text-brand-orange':'text-zinc-600 hover:bg-[#F5F4F0]'}`}><I size={16}/>{String(label)}</button>})}</div></div><div className="p-5 sm:p-6"><div><h2 className="text-lg font-extrabold text-brand-ink">Tyre intelligence rules</h2><p className="mt-1 text-xs text-zinc-400">These values are prototype defaults until backend configuration is connected.</p></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold text-zinc-600">Critical tread threshold (mm)<input type="number" step="0.1" value={criticalTread} onChange={e=>setCriticalTread(Number(e.target.value))} className={`mt-2 w-full ${inputClass}`}/></label><label className="text-xs font-bold text-zinc-600">Attention tread threshold (mm)<input type="number" step="0.1" value={attentionTread} onChange={e=>setAttentionTread(Number(e.target.value))} className={`mt-2 w-full ${inputClass}`}/></label></div><div className="mt-8 border-t border-black/[0.05] pt-6"><h2 className="text-lg font-extrabold text-brand-ink">Automatic notification rules</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold text-zinc-600">Critical reminder cooldown (hours)<input type="number" value={criticalCooldown} onChange={e=>setCriticalCooldown(Number(e.target.value))} className={`mt-2 w-full ${inputClass}`}/></label><label className="text-xs font-bold text-zinc-600">Attention reminder cooldown (days)<input type="number" value={attentionCooldown} onChange={e=>setAttentionCooldown(Number(e.target.value))} className={`mt-2 w-full ${inputClass}`}/></label><label className="text-xs font-bold text-zinc-600">Maximum customer reminders<input type="number" value={maxReminders} onChange={e=>setMaxReminders(Number(e.target.value))} className={`mt-2 w-full ${inputClass}`}/></label><div className="grid grid-cols-2 gap-3"><label className="text-xs font-bold text-zinc-600">Quiet from<input type="time" value={quietStart} onChange={e=>setQuietStart(e.target.value)} className={`mt-2 w-full ${inputClass}`}/></label><label className="text-xs font-bold text-zinc-600">Quiet until<input type="time" value={quietEnd} onChange={e=>setQuietEnd(e.target.value)} className={`mt-2 w-full ${inputClass}`}/></label></div></div></div></div></div></section></div>;
}
