import { useEffect, useState } from 'react';
import { BellRing, Building2, CheckCircle2, RotateCcw, Save, ShieldCheck, Users } from 'lucide-react';
import { PageHeader } from '../components/ui/PageHeader';

type Tab='Organisation'|'Users & roles'|'Tyre rules'|'Notifications';
type Settings={branchName:string;branchCode:string;phone:string;manager:string;criticalTread:number;attentionTread:number;criticalCooldown:number;attentionCooldown:number;maxReminders:number;quietStart:string;quietEnd:string;autoCritical:boolean;autoAttention:boolean};
const defaults:Settings={branchName:'Durban Central',branchCode:'DBN-01',phone:'031 555 0180',manager:'N. Mthembu',criticalTread:2.2,attentionTread:3.5,criticalCooldown:48,attentionCooldown:7,maxReminders:2,quietStart:'20:00',quietEnd:'07:00',autoCritical:true,autoAttention:true};
const inputClass='h-11 w-full rounded-xl border border-black/[0.07] bg-white px-3 text-sm outline-none focus:border-orange-200 focus:ring-4 focus:ring-orange-100/50';
const roles=[['Administrator','Full system access'],['Service advisor','Customers, bookings and notifications'],['Technician','Inspections, vehicles and tyre records'],['Manager','Operational oversight and reports']];
function load(){try{return {...defaults,...JSON.parse(localStorage.getItem('tyretrack.demo.settings')??'{}')} as Settings}catch{return defaults}}
export default function SettingsPage(){
 const [tab,setTab]=useState<Tab>('Organisation');const [settings,setSettings]=useState<Settings>(defaults);const [saved,setSaved]=useState(false);const [dirty,setDirty]=useState(false);
 useEffect(()=>setSettings(load()),[]);const update=<K extends keyof Settings>(key:K,value:Settings[K])=>{setSettings(s=>({...s,[key]:value}));setDirty(true)};
 const save=()=>{localStorage.setItem('tyretrack.demo.settings',JSON.stringify(settings));setDirty(false);setSaved(true);setTimeout(()=>setSaved(false),1800)};const reset=()=>{setSettings(defaults);setDirty(true)};
 const nav:[Tab,typeof Building2][]=[['Organisation',Building2],['Users & roles',Users],['Tyre rules',ShieldCheck],['Notifications',BellRing]];
 return <div className="space-y-6"><PageHeader eyebrow="System administration" title="Settings" description="Configure operational rules used across TyreTrack." action={<div className="flex gap-2"><button onClick={reset} className="inline-flex h-11 items-center gap-2 rounded-xl bg-white px-4 text-sm font-bold text-zinc-600 ring-1 ring-black/[0.07]"><RotateCcw size={15}/>Reset</button><button onClick={save} className="inline-flex h-11 items-center gap-2 rounded-xl bg-[#202124] px-4 text-sm font-bold text-white"><Save size={16}/>{dirty?'Save changes':'Save settings'}</button></div>}/>{saved&&<div className="flex items-center gap-2 rounded-xl bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-700"><CheckCircle2 size={16}/>Settings saved. Refreshing the page will keep these values.</div>}
 <section className="overflow-hidden rounded-[24px] bg-white ring-1 ring-black/[0.045]"><div className="grid lg:grid-cols-[250px_1fr]"><nav className="border-b border-black/[0.05] p-5 lg:border-b-0 lg:border-r"><div className="space-y-2">{nav.map(([label,Icon])=><button onClick={()=>setTab(label)} key={label} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-bold transition ${tab===label?'bg-orange-50 text-brand-orange':'text-zinc-600 hover:bg-[#F5F4F0]'}`}><Icon size={16}/>{label}</button>)}</div></nav><div className="p-5 sm:p-6">\ {tab==='Organisation'&&<div><h2 className="text-lg font-extrabold text-brand-ink">Organisation</h2><p className="mt-1 text-xs text-zinc-400">Branch details used in operational screens and customer communication.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold text-zinc-600">Branch name<input value={settings.branchName} onChange={e=>update('branchName',e.target.value)} className={`mt-2 ${inputClass}`}/></label><label className="text-xs font-bold text-zinc-600">Branch code<input value={settings.branchCode} onChange={e=>update('branchCode',e.target.value)} className={`mt-2 ${inputClass}`}/></label><label className="text-xs font-bold text-zinc-600">Contact number<input value={settings.phone} onChange={e=>update('phone',e.target.value)} className={`mt-2 ${inputClass}`}/></label><label className="text-xs font-bold text-zinc-600">Branch manager<input value={settings.manager} onChange={e=>update('manager',e.target.value)} className={`mt-2 ${inputClass}`}/></label></div></div>}
 {tab==='Users & roles'&&<div><h2 className="text-lg font-extrabold text-brand-ink">Users & roles</h2><p className="mt-1 text-xs text-zinc-400">Frontend permission model that the backend will enforce later.</p><div className="mt-5 divide-y divide-black/[0.05] border-y border-black/[0.05]">{roles.map(([role,scope])=><div key={role} className="flex items-center justify-between gap-4 py-4"><div><p className="text-sm font-extrabold text-brand-ink">{role}</p><p className="mt-1 text-xs text-zinc-400">{scope}</p></div><button onClick={()=>alert(`${role} permissions are configured for the frontend prototype. Backend authorization will enforce them in production.`)} className="rounded-xl bg-[#F5F4F0] px-3 py-2 text-xs font-bold text-zinc-600 hover:bg-orange-50 hover:text-brand-orange">View permissions</button></div>)}</div></div>}
 {tab==='Tyre rules'&&<div><h2 className="text-lg font-extrabold text-brand-ink">Tyre intelligence rules</h2><p className="mt-1 text-xs text-zinc-400">Thresholds used to classify verified tread measurements.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold text-zinc-600">Critical tread threshold (mm)<input type="number" min="0" step="0.1" value={settings.criticalTread} onChange={e=>update('criticalTread',Number(e.target.value))} className={`mt-2 ${inputClass}`}/></label><label className="text-xs font-bold text-zinc-600">Attention tread threshold (mm)<input type="number" min="0" step="0.1" value={settings.attentionTread} onChange={e=>update('attentionTread',Number(e.target.value))} className={`mt-2 ${inputClass}`}/></label></div><div className="mt-5 rounded-xl bg-amber-50 p-4 text-xs leading-5 text-amber-800">Critical must remain below Attention. Current rule: ≤ {settings.criticalTread.toFixed(1)} mm critical; ≤ {settings.attentionTread.toFixed(1)} mm attention.</div></div>}
 {tab==='Notifications'&&<div><h2 className="text-lg font-extrabold text-brand-ink">Automatic notification rules</h2><p className="mt-1 text-xs text-zinc-400">Control when TyreTrack contacts customers and when it stays quiet.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold text-zinc-600">Critical reminder cooldown (hours)<input type="number" min="1" value={settings.criticalCooldown} onChange={e=>update('criticalCooldown',Number(e.target.value))} className={`mt-2 ${inputClass}`}/></label><label className="text-xs font-bold text-zinc-600">Attention reminder cooldown (days)<input type="number" min="1" value={settings.attentionCooldown} onChange={e=>update('attentionCooldown',Number(e.target.value))} className={`mt-2 ${inputClass}`}/></label><label className="text-xs font-bold text-zinc-600">Maximum customer reminders<input type="number" min="0" value={settings.maxReminders} onChange={e=>update('maxReminders',Number(e.target.value))} className={`mt-2 ${inputClass}`}/></label><div className="grid grid-cols-2 gap-3"><label className="text-xs font-bold text-zinc-600">Quiet from<input type="time" value={settings.quietStart} onChange={e=>update('quietStart',e.target.value)} className={`mt-2 ${inputClass}`}/></label><label className="text-xs font-bold text-zinc-600">Quiet until<input type="time" value={settings.quietEnd} onChange={e=>update('quietEnd',e.target.value)} className={`mt-2 ${inputClass}`}/></label></div></div><div className="mt-6 divide-y divide-black/[0.05] border-y border-black/[0.05]"><label className="flex items-center justify-between gap-4 py-4 text-sm font-bold text-brand-ink">Automatic critical safety alerts<input type="checkbox" checked={settings.autoCritical} onChange={e=>update('autoCritical',e.target.checked)} className="h-5 w-5 accent-orange-500"/></label><label className="flex items-center justify-between gap-4 py-4 text-sm font-bold text-brand-ink">Automatic attention reminders<input type="checkbox" checked={settings.autoAttention} onChange={e=>update('autoAttention',e.target.checked)} className="h-5 w-5 accent-orange-500"/></label></div></div>}
 </div></div></section></div>;
}
