import { Filter, Plus, QrCode, Search } from 'lucide-react';
import { Link } from 'react-router-dom';
import { PageHeader } from '../components/ui/PageHeader';
import { StatusBadge } from '../components/ui/StatusBadge';
import { tyres } from '../data/mock';

export default function TyresPage() {
  return <div className="space-y-6"><PageHeader eyebrow="Tyre lifecycle" title="Tyres" description="Every registered tyre has a digital identity, current wheel position and complete lifecycle history." action={<button className="inline-flex h-10 items-center gap-2 rounded-xl bg-brand-orange px-4 text-sm font-bold text-white"><Plus size={17}/>Register tyre</button>}/><div className="flex flex-col gap-3 md:flex-row"><div className="relative flex-1 md:max-w-md"><Search size={17} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-zinc-400"/><input placeholder="Search tyre ID, brand or vehicle..." className="h-11 w-full rounded-xl border border-brand-line bg-white pl-10 pr-4 text-sm outline-none focus:border-brand-orange"/></div><button className="inline-flex h-11 items-center justify-center gap-2 rounded-xl border border-brand-line bg-white px-4 text-sm font-semibold text-brand-muted"><Filter size={16}/>Filters</button><button className="inline-flex h-11 items-center justify-center gap-2 rounded-xl border border-brand-line bg-white px-4 text-sm font-semibold text-brand-muted"><QrCode size={16}/>Scan QR</button></div><div className="grid gap-4 xl:grid-cols-2">{tyres.map(tyre => <Link to={`/tyres/${tyre.id}`} key={tyre.id} className="rounded-2xl border border-brand-line bg-white p-5 shadow-soft transition hover:-translate-y-0.5 hover:border-orange-200"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-brand-orange">{tyre.reference}</p><h3 className="mt-1 text-lg font-bold">{tyre.brand} {tyre.model}</h3><p className="mt-1 text-sm text-brand-muted">{tyre.size} · {tyre.vehicle}</p></div><StatusBadge status={tyre.status}/></div><div className="mt-5 grid grid-cols-4 gap-2 border-t border-brand-line pt-4 text-sm"><div><p className="text-xs text-brand-muted">Position</p><p className="mt-1 font-semibold">{tyre.position}</p></div><div><p className="text-xs text-brand-muted">Mileage</p><p className="mt-1 font-semibold">{tyre.mileage.toLocaleString('en-ZA')}</p></div><div><p className="text-xs text-brand-muted">Tread</p><p className="mt-1 font-semibold">{tyre.tread.toFixed(1)} mm</p></div><div><p className="text-xs text-brand-muted">Fitted</p><p className="mt-1 font-semibold">{tyre.fittedOn}</p></div></div></Link>)}</div></div>;
}
