import { useMemo, useState } from 'react';
import { ArrowLeft, CheckCircle2, Gauge, RadioTower, Save, ShieldCheck } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { tyres } from '../data/mock';
import { evaluateTyreHealth } from '../lib/tyreHealthEngine';
import { workflowStore, type DemoInspection, type DemoJobCard, type DemoJobCardItem, type MeasurementSource } from '../lib/workflowStore';

const positions=['Front Left','Front Right','Rear Left','Rear Right'] as const;
type Reading={source:MeasurementSource;inner?:number;centre?:number;outer?:number;pressure?:number;wearPattern:string;deviceName?:string};
const empty=():Reading=>({source:'Manual gauge',wearPattern:'Even'});
const input='h-10 w-full rounded-xl border border-black/[0.07] bg-white px-3 text-sm outline-none focus:border-orange-300';

export default function VehicleInspectionPage(){
 const navigate=useNavigate();const vehicles=workflowStore.vehicles();const customers=workflowStore.customers();const [registration,setRegistration]=useState(vehicles[0]?.registration??'');const vehicle=vehicles.find(v=>v.registration===registration);const customer=customers.find(c=>c.id===vehicle?.customerId);const [odometer,setOdometer]=useState(vehicle?.mileage??0);const [active,setActive]=useState(0);const [readings,setReadings]=useState<Record<string,Reading>>(()=>Object.fromEntries(positions.map(p=>[p,empty()])));const [saved,setSaved]=useState(false);
 const tpms=workflowStore.tpms().filter(r=>r.registration===registration);const deviceOptions=workflowStore.devices().filter(d=>d.status==='Connected');
 const update=(position:string,patch:Partial<Reading>)=>setReadings(r=>({...r,[position]:{...r[position],...patch}}));
 const results=useMemo(()=>Object.fromEntries(positions.map(p=>{const r=readings[p];const vals=[r.inner,r.centre,r.outer].filter((v):v is number=>typeof v==='number'&&v>0);const avg=vals.length===3?vals.reduce((a,b)=>a+b,0)/3:undefined;return [p,evaluateTyreHealth({measuredTreadMm:avg,abnormalWear:r.wearPattern!=='Even'})]})),[readings]);
 const complete=positions.every(p=>{const r=readings[p];return [r.inner,r.centre,r.outer].every(v=>typeof v==='number'&&v>0)&&typeof r.pressure==='number'&&r.pressure>0});
 const save=()=>{if(!vehicle||!customer||!complete)return;const now=Date.now();const records:DemoInspection[]=positions.map((p,i)=>{const r=readings[p];const tyre=tyres.find(t=>t.vehicle===registration&&t.position.toLowerCase()===p.toLowerCase());const tp=tpms.find(t=>t.position===p);return {id:`INS-${now}-${i+1}`,registration,customer:customer.name,technician:'Current technician',status:'Completed',tyreId:tyre?.id,odometer,position:p,inner:r.inner,centre:r.centre,outer:r.outer,pressure:r.pressure,tpmsPressure:tp?.pressurePsi,measurementSource:r.source,deviceName:r.deviceName,wearPattern:r.wearPattern,defects:[],recommendation:results[p].action};});workflowStore.saveInspections([...records,...workflowStore.inspections()]);
 const jobItems:DemoJobCardItem[]=[];positions.forEach((p,i)=>{const result=results[p];const tyre=tyres.find(t=>t.vehicle===registration&&t.position.toLowerCase()===p.toLowerCase());if(result.status==='Critical'){jobItems.push({id:`ITEM-${now}-${i}-R`,type:'Tyre replacement',description:`Replace ${p.toLowerCase()} tyre${tyre?` - ${tyre.brand} ${tyre.model} ${tyre.size}`:''}`,position:p,quantity:1,unitPrice:tyre?.size==='205/55 R16'?1850:2100,approved:true});jobItems.push({id:`ITEM-${now}-${i}-B`,type:'Balancing',description:`Balance replacement wheel - ${p}`,position:p,quantity:1,unitPrice:180,approved:true})}if(result.status==='Attention'&&readings[p].wearPattern!=='Even'){jobItems.push({id:`ITEM-${now}-${i}-A`,type:'Alignment',description:`Alignment check after ${readings[p].wearPattern.toLowerCase()} on ${p}`,position:p,quantity:1,unitPrice:650,approved:true})}});
 if(jobItems.length){const branch=workflowStore.branches().find(b=>b.id===vehicle.branchId)?.name??'Durban Central';const card:DemoJobCard={id:`JOB-${now}`,registration,customer:customer.name,branch,inspectionIds:records.map(r=>r.id),createdAt:new Date().toISOString(),status:'Draft',quoteNumber:`QT-${new Date().toISOString().slice(2,10).replace(/-/g,'')}-${String(workflowStore.jobCards().length+1).padStart(3,'0')}`,quoteDecision:'Pending',items:jobItems,vatRate:15};workflowStore.saveJobCards([card,...workflowStore.jobCards()])}
 setSaved(true);setTimeout(()=>navigate(jobItems.length?'/job-cards':'/inspections'),900)};
 const current=positions[active];const reading=readings[current];const currentTpms=tpms.find(t=>t.position===current);
 return <div className="mx-auto max-w-7xl space-y-6"><div className="flex items-center justify-between"><Link to="/inspections" className="inline-flex items-center gap-2 text-sm font-bold text-zinc-500"><ArrowLeft size={16}/>Inspections</Link>{saved&&<span className="inline-flex items-center gap-2 text-sm font-bold text-emerald-700"><CheckCircle2 size={16}/>Inspection saved</span>}</div><div><p className="text-xs font-bold uppercase tracking-[.14em] text-brand-orange">Complete vehicle tyre inspection</p><h1 className="mt-2 text-3xl font-extrabold">Inspect all four tyres in one visit</h1><p className="mt-2 text-sm text-zinc-500">Capture each wheel position, compare TPMS where available, and automatically create workshop work when the findings require action.</p></div>
 <section className="rounded-[24px] bg-white p-5 ring-1 ring-black/[0.05]"><div className="grid gap-4 md:grid-cols-3"><label className="text-xs font-bold text-zinc-600">Vehicle<select value={registration} onChange={e=>{setRegistration(e.target.value);const v=vehicles.find(x=>x.registration===e.target.value);setOdometer(v?.mileage??0)}} className={`mt-2 ${input}`}>{vehicles.map(v=><option key={v.id}>{v.registration}</option>)}</select></label><label className="text-xs font-bold text-zinc-600">Customer<input readOnly value={customer?.name??''} className={`mt-2 ${input} bg-zinc-50`}/></label><label className="text-xs font-bold text-zinc-600">Odometer<input type="number" value={odometer} onChange={e=>setOdometer(Number(e.target.value))} className={`mt-2 ${input}`}/></label></div></section>
 <div className="grid gap-5 lg:grid-cols-[300px_1fr]"><aside className="space-y-3 rounded-[24px] bg-[#202124] p-4 text-white"><p className="px-2 text-xs font-bold uppercase tracking-[.14em] text-zinc-500">Wheel positions</p>{positions.map((p,i)=>{const r=readings[p];const done=[r.inner,r.centre,r.outer,r.pressure].every(v=>typeof v==='number'&&v>0);const result=results[p];return <button key={p} onClick={()=>setActive(i)} className={`w-full rounded-2xl p-4 text-left transition ${i===active?'bg-white/10 ring-1 ring-orange-400/30':'bg-white/[0.04] hover:bg-white/[0.07]'}`}><div className="flex items-center justify-between"><div><p className="text-sm font-extrabold">{p}</p><p className="mt-1 text-xs text-zinc-400">{done?`${result.status} · ${result.treadLabel}`:'Not complete'}</p></div><span className={`h-3 w-3 rounded-full ${done?(result.status==='Critical'?'bg-red-500':result.status==='Attention'?'bg-amber-400':'bg-emerald-400'):'bg-zinc-700'}`}/></div></button>})}</aside>
 <section className="rounded-[24px] bg-white p-5 ring-1 ring-black/[0.05] sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.12em] text-brand-orange">Tyre {active+1} of 4</p><h2 className="mt-1 text-xl font-extrabold">{current}</h2></div>{currentTpms?<div className={`rounded-xl px-3 py-2 text-xs font-bold ${currentTpms.status==='Normal'?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}><RadioTower size={14} className="mr-1 inline"/>TPMS {currentTpms.pressurePsi} PSI · {currentTpms.status}</div>:<span className="rounded-xl bg-zinc-100 px-3 py-2 text-xs font-bold text-zinc-500">No TPMS data</span>}</div>
 <div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold text-zinc-600">Measurement source<select value={reading.source} onChange={e=>update(current,{source:e.target.value as MeasurementSource})} className={`mt-2 ${input}`}><option>Manual gauge</option><option>Connected device</option><option>Drive-over scanner</option><option>TPMS</option><option>Phone camera</option></select></label><label className="text-xs font-bold text-zinc-600">Connected device<select value={reading.deviceName??''} onChange={e=>update(current,{deviceName:e.target.value})} className={`mt-2 ${input}`}><option value="">None / manual</option>{deviceOptions.map(d=><option key={d.id}>{d.name}</option>)}</select></label></div>
 <div className="mt-5 grid grid-cols-3 gap-3">{(['inner','centre','outer'] as const).map(k=><label key={k} className="text-xs font-bold capitalize text-zinc-600">{k} tread (mm)<input type="number" step="0.1" min="0" value={reading[k]??''} onChange={e=>update(current,{[k]:e.target.value?Number(e.target.value):undefined})} className={`mt-2 ${input}`}/></label>)}</div><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold text-zinc-600">Workshop pressure (PSI)<input type="number" value={reading.pressure??''} onChange={e=>update(current,{pressure:e.target.value?Number(e.target.value):undefined})} className={`mt-2 ${input}`}/></label><label className="text-xs font-bold text-zinc-600">Wear pattern<select value={reading.wearPattern} onChange={e=>update(current,{wearPattern:e.target.value})} className={`mt-2 ${input}`}><option>Even</option><option>Inner-edge wear</option><option>Outer-edge wear</option><option>Centre wear</option><option>Cupping</option></select></label></div>
 <div className="mt-5 rounded-2xl bg-[#F7F6F2] p-4"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.12em] text-zinc-400">Live tyre result</p><p className="mt-1 text-lg font-extrabold">{results[current].status}</p></div><Gauge size={22} className="text-brand-orange"/></div><p className="mt-2 text-sm text-zinc-600">{results[current].action}</p></div><div className="mt-5 flex justify-between gap-3"><button disabled={active===0} onClick={()=>setActive(i=>Math.max(0,i-1))} className="h-11 rounded-xl bg-zinc-100 px-4 text-sm font-bold disabled:opacity-30">Previous tyre</button>{active<3?<button onClick={()=>setActive(i=>Math.min(3,i+1))} className="h-11 rounded-xl bg-[#202124] px-4 text-sm font-bold text-white">Next tyre</button>:<button disabled={!complete} onClick={save} className="inline-flex h-11 items-center gap-2 rounded-xl bg-brand-orange px-5 text-sm font-bold text-white disabled:opacity-35"><Save size={16}/>Complete vehicle inspection</button>}</div></section></div>{!complete&&<div className="flex items-center gap-3 rounded-2xl bg-amber-50 p-4 text-sm text-amber-800"><ShieldCheck size={18}/>Complete tread and workshop pressure for all four tyres before closing the vehicle inspection.</div>}</div>;
}
