import { useState } from 'react';
import { ArrowLeft, CarFront, CheckCircle2 } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { PageHeader } from '../components/ui/PageHeader';
import { workflowStore, type DemoVehicle } from '../lib/workflowStore';

export default function VehicleCreatePage(){
 const navigate=useNavigate();const customers=workflowStore.customers();
 const [customerId,setCustomerId]=useState(customers[0]?.id??'');const [registration,setRegistration]=useState('');const [make,setMake]=useState('');const [model,setModel]=useState('');const [year,setYear]=useState(new Date().getFullYear());const [mileage,setMileage]=useState(0);const [error,setError]=useState('');
 const submit=()=>{if(!customerId||!registration.trim()||!make.trim()||!model.trim()){setError('Customer, registration, make and model are required.');return;}const vehicles=workflowStore.vehicles();if(vehicles.some(v=>v.registration.toLowerCase()===registration.trim().toLowerCase())){setError('A vehicle with this registration already exists.');return;}const vehicle:DemoVehicle={id:`VEH-${Date.now()}`,customerId,registration:registration.trim().toUpperCase(),make:make.trim(),model:model.trim(),year:Number(year),mileage:Number(mileage)||0,status:'Active'};workflowStore.saveVehicles([vehicle,...vehicles]);navigate(`/vehicles/${vehicle.id}`)};
 return <div className="space-y-6"><PageHeader eyebrow="Vehicle registry" title="Register vehicle" description="Add a customer or fleet vehicle and connect it to tyre lifecycle records." action={<Link to="/vehicles" className="inline-flex h-11 items-center gap-2 rounded-xl bg-white px-4 text-sm font-bold text-zinc-600 ring-1 ring-black/[0.06]"><ArrowLeft size={16}/>Back to vehicles</Link>}/>
 <section className="mx-auto max-w-3xl rounded-[26px] bg-white p-6 ring-1 ring-black/[0.045] sm:p-7"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-orange-50 text-brand-orange"><CarFront size={19}/></div><div><h2 className="text-lg font-extrabold text-brand-ink">Vehicle details</h2><p className="mt-1 text-xs text-zinc-400">Register the vehicle before fitting or inspecting tyres.</p></div></div>{error&&<div className="mt-5 rounded-xl bg-red-50 px-4 py-3 text-sm font-bold text-red-700">{error}</div>}<div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold text-zinc-600">Customer<select value={customerId} onChange={e=>setCustomerId(e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-black/[0.08] px-3 text-sm">{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="text-xs font-bold text-zinc-600">Registration<input value={registration} onChange={e=>setRegistration(e.target.value)} placeholder="ND 123-456" className="mt-2 h-11 w-full rounded-xl border border-black/[0.08] px-3 text-sm"/></label><label className="text-xs font-bold text-zinc-600">Make<input value={make} onChange={e=>setMake(e.target.value)} placeholder="Toyota" className="mt-2 h-11 w-full rounded-xl border border-black/[0.08] px-3 text-sm"/></label><label className="text-xs font-bold text-zinc-600">Model<input value={model} onChange={e=>setModel(e.target.value)} placeholder="Corolla Cross" className="mt-2 h-11 w-full rounded-xl border border-black/[0.08] px-3 text-sm"/></label><label className="text-xs font-bold text-zinc-600">Year<input type="number" value={year} onChange={e=>setYear(Number(e.target.value))} className="mt-2 h-11 w-full rounded-xl border border-black/[0.08] px-3 text-sm"/></label><label className="text-xs font-bold text-zinc-600">Odometer (km)<input type="number" min="0" value={mileage} onChange={e=>setMileage(Number(e.target.value))} className="mt-2 h-11 w-full rounded-xl border border-black/[0.08] px-3 text-sm"/></label></div><button onClick={submit} className="mt-6 inline-flex h-11 items-center gap-2 rounded-xl bg-brand-orange px-5 text-sm font-extrabold text-white"><CheckCircle2 size={16}/>Register vehicle</button></section></div>;
}