import { useMemo, useState } from 'react';
import { ArrowLeft, Gauge, Save, UserRound } from 'lucide-react';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { workflowStore, type DemoVehicle } from '../lib/workflowStore';
import { tyres } from '../data/mock';

const inputClass='h-11 w-full rounded-xl border border-black/[0.07] bg-white px-3 text-sm outline-none focus:border-orange-200 focus:ring-4 focus:ring-orange-100/50';
export default function VehicleWorkspacePage(){
  const { vehicleId }=useParams();const [params]=useSearchParams();const navigate=useNavigate();const creating=vehicleId==='new';
  const vehicles=workflowStore.vehicles();const customers=workflowStore.customers();
  const base=vehicles.find(v=>v.id===vehicleId)??{id:`VEH-${Date.now()}`,customerId:params.get('customer')??customers[0]?.id??'',registration:'',make:'',model:'',year:new Date().getFullYear(),mileage:0,status:'Active' as const};
  const [form,setForm]=useState<DemoVehicle>(base);
  const owner=customers.find(c=>c.id===form.customerId);const fitted=useMemo(()=>tyres.filter(t=>t.vehicle===form.registration),[form.registration]);
  const save=()=>{workflowStore.saveVehicles(creating?[...vehicles,form]:vehicles.map(v=>v.id===form.id?form:v));navigate('/vehicles');};
  return <div className="mx-auto max-w-6xl space-y-6"><Link to="/vehicles" className="inline-flex items-center gap-2 text-sm font-semibold text-zinc-500 hover:text-brand-ink"><ArrowLeft size={16}/>Vehicles</Link>
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.17em] text-brand-orange">Vehicle record</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight text-brand-ink">{creating?'Register vehicle':`${form.make} ${form.model}`}</h1><p className="mt-2 text-sm text-zinc-500">Ownership, odometer and fitted tyre context.</p></div><button onClick={save} disabled={!form.registration||!form.make||!form.model||!form.customerId} className="inline-flex h-11 items-center gap-2 rounded-xl bg-[#202124] px-4 text-sm font-bold text-white disabled:opacity-40"><Save size={16}/>{creating?'Register vehicle':'Save changes'}</button></div>
    <div className="grid gap-5 lg:grid-cols-[0.9fr_1.1fr]"><section className="rounded-[24px] bg-white p-5 ring-1 ring-black/[0.045] sm:p-6"><h2 className="font-extrabold text-brand-ink">Vehicle details</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold text-zinc-600">Registration<input value={form.registration} onChange={e=>setForm({...form,registration:e.target.value})} className={`mt-2 ${inputClass}`}/></label><label className="text-xs font-bold text-zinc-600">Owner<select value={form.customerId} onChange={e=>setForm({...form,customerId:e.target.value})} className={`mt-2 ${inputClass}`}>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="text-xs font-bold text-zinc-600">Make<input value={form.make} onChange={e=>setForm({...form,make:e.target.value})} className={`mt-2 ${inputClass}`}/></label><label className="text-xs font-bold text-zinc-600">Model<input value={form.model} onChange={e=>setForm({...form,model:e.target.value})} className={`mt-2 ${inputClass}`}/></label><label className="text-xs font-bold text-zinc-600">Year<input type="number" value={form.year} onChange={e=>setForm({...form,year:Number(e.target.value)})} className={`mt-2 ${inputClass}`}/></label><label className="text-xs font-bold text-zinc-600">Current odometer<input type="number" value={form.mileage} onChange={e=>setForm({...form,mileage:Number(e.target.value)})} className={`mt-2 ${inputClass}`}/></label></div></section>
      <section className="rounded-[24px] bg-white p-5 ring-1 ring-black/[0.045] sm:p-6"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#F2F1ED] text-zinc-600"><UserRound size={17}/></div><div><p className="text-xs text-zinc-400">Owner</p><p className="text-sm font-bold text-brand-ink">{owner?.name??'Not linked'}</p></div></div><div className="mt-6 border-t border-black/[0.05] pt-5"><div className="flex items-center justify-between"><div><h2 className="font-extrabold text-brand-ink">Current tyre set</h2><p className="mt-1 text-xs text-zinc-400">Registered tyres currently linked by vehicle registration.</p></div><Gauge size={18} className="text-brand-orange"/></div><div className="mt-4 divide-y divide-black/[0.05]">{fitted.length?fitted.map(t=><Link to={`/tyres/${t.id}`} key={t.id} className="flex items-center justify-between py-3"><div><p className="text-sm font-bold text-brand-ink">{t.brand} {t.model}</p><p className="mt-1 text-xs text-zinc-400">{t.position} · {t.size}</p></div><span className="text-xs font-bold text-zinc-500">{t.tread.toFixed(1)} mm</span></Link>):<p className="py-8 text-center text-sm text-zinc-400">No fitted tyre records found.</p>}</div></div></section></div>
  </div>;
}
