import { useState } from 'react';
import { ArrowLeft, CheckCircle2, ShieldPlus } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { PageHeader } from '../components/ui/PageHeader';
import { workflowStore, type DemoWarrantyClaim } from '../lib/workflowStore';

export default function WarrantyCreatePage(){
 const navigate=useNavigate();const [tyreId,setTyreId]=useState('');const [issue,setIssue]=useState('');const [type,setType]=useState('Manufacturer warranty');const [supplier,setSupplier]=useState('');const [notes,setNotes]=useState('');const [error,setError]=useState('');
 const submit=()=>{if(!tyreId.trim()||!issue.trim()||!supplier.trim()){setError('Tyre ID, issue and supplier are required.');return;}const claims=workflowStore.warranty();const claim:DemoWarrantyClaim={id:`WAR-${Date.now()}`,tyreId:tyreId.trim().toUpperCase(),issue:issue.trim(),type,status:'Evidence review',eligibility:'Pending assessment',supplier:supplier.trim(),notes:notes.trim()||undefined};workflowStore.saveWarranty([claim,...claims]);navigate(`/warranty/${claim.id}`)};
 return <div className="space-y-6"><PageHeader eyebrow="After-sale protection" title="Start warranty claim" description="Create a claim and capture the tyre, issue and supplier details for evidence review." action={<Link to="/warranty" className="inline-flex h-11 items-center gap-2 rounded-xl bg-white px-4 text-sm font-bold text-zinc-600 ring-1 ring-black/[0.06]"><ArrowLeft size={16}/>Back to warranty</Link>}/><section className="mx-auto max-w-3xl rounded-[26px] bg-white p-6 ring-1 ring-black/[0.045] sm:p-7"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-orange-50 text-brand-orange"><ShieldPlus size={19}/></div><div><h2 className="text-lg font-extrabold text-brand-ink">Claim details</h2><p className="mt-1 text-xs text-zinc-400">Inspection evidence can be reviewed after the claim is created.</p></div></div>{error&&<div className="mt-5 rounded-xl bg-red-50 px-4 py-3 text-sm font-bold text-red-700">{error}</div>}<div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold text-zinc-600">Tyre ID<input value={tyreId} onChange={e=>setTyreId(e.target.value)} placeholder="TYR-3004" className="mt-2 h-11 w-full rounded-xl border border-black/[0.08] px-3 text-sm"/></label><label className="text-xs font-bold text-zinc-600">Cover type<select value={type} onChange={e=>setType(e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-black/[0.08] px-3 text-sm"><option>Manufacturer warranty</option><option>Road-hazard plan</option><option>Fleet protection plan</option></select></label><label className="text-xs font-bold text-zinc-600 sm:col-span-2">Issue<input value={issue} onChange={e=>setIssue(e.target.value)} placeholder="Describe the tyre issue" className="mt-2 h-11 w-full rounded-xl border border-black/[0.08] px-3 text-sm"/></label><label className="text-xs font-bold text-zinc-600">Supplier<input value={supplier} onChange={e=>setSupplier(e.target.value)} placeholder="Continental" className="mt-2 h-11 w-full rounded-xl border border-black/[0.08] px-3 text-sm"/></label><label className="text-xs font-bold text-zinc-600 sm:col-span-2">Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} className="mt-2 min-h-24 w-full rounded-xl border border-black/[0.08] p-3 text-sm" placeholder="Optional notes"/></label></div><button onClick={submit} className="mt-6 inline-flex h-11 items-center gap-2 rounded-xl bg-brand-orange px-5 text-sm font-extrabold text-white"><CheckCircle2 size={16}/>Create claim</button></section></div>;
}